### ISSUE TITLE
Docker on OS X

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#107]
When I try to install on OS X using the docker, I get this : 

```
app_1         | scripts/app.sh: line 45: [: =: unary operator expected
app_1         | *** Starting uWSGI 2.0.12 (64bit) on [Wed May 11 06:40:52 2016] ***
app_1         | compiled with version: 4.9.2 on 19 March 2016 10:08:28
app_1         | os: Linux-4.4.8-boot2docker #1 SMP Mon Apr 25 21:57:27 UTC 2016
app_1         | nodename: f468b4ae050d
app_1         | machine: x86_64
app_1         | clock source: unix
app_1         | detected number of CPU cores: 1
app_1         | current working directory: /srv/app
app_1         | detected binary path: /opt/miniconda/bin/uwsgi
app_1         | !!! no internal routing support, rebuild with pcre support !!!
app_1         | setgid() to 33
app_1         | setuid() to 33
app_1         | chdir() to /srv/app
app_1         | your processes number limit is 1048576
app_1         | your memory page size is 4096 bytes
app_1         | detected max file descriptor number: 1048576
app_1         | lock engine: pthread robust mutexes
app_1         | thunder lock: disabled (you can enable it with --thunder-lock)
app_1         | uwsgi socket 0 bound to TCP address :8000 fd 3
app_1         | Python version: 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
app_1         | Python main interpreter initialized at 0xb98e40
app_1         | python threads support enabled
app_1         | your server socket listen backlog is limited to 100 connections
app_1         | your mercy for graceful operations on workers is 60 seconds
app_1         | mapped 1304064 bytes (1273 KB) for 64 cores
app_1         | *** Operational MODE: preforking+threaded ***
app_1         | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xb98e40 pid: 119 (default app)
app_1         | *** uWSGI is running in multiple interpreter mode ***
app_1         | spawned uWSGI master process (pid: 119)
app_1         | spawned uWSGI worker 1 (pid: 126, cores: 8)
app_1         | spawned uWSGI worker 2 (pid: 127, cores: 8)
app_1         | spawned uWSGI worker 3 (pid: 128, cores: 8)
app_1         | spawned uWSGI worker 4 (pid: 129, cores: 8)
app_1         | spawned uWSGI worker 5 (pid: 130, cores: 8)
app_1         | spawned uWSGI worker 6 (pid: 147, cores: 8)
app_1         | spawned uWSGI worker 7 (pid: 156, cores: 8)
app_1         | spawned uWSGI worker 8 (pid: 173, cores: 8)
app_1         | Python auto-reloader enabled
app_1         | Indexing 0 items
app_1         | Indexing 0 collections
app_1         | Indexing 0 corpus
app_1         | Indexing 0 fonds
db_1          | 2016-05-11T06:40:56.740373Z 13 [Note] Aborted connection 13 to db: 'telemeta' user: 'telemeta' host: '172.17.0.6' (Got an error reading communication packets)

```

**Comment by yomguy** [comment]
Hi @AnasGhrab 
Those little errors shouldn't be a pb. Do you get the web UI ?

**Comment by AnasGhrab** [comment]
The web page can't load... http://<IP>:8000

```
Ce site est inaccessible

172.17.0.3 a mis trop de temps à répondre.
```

**Comment by yomguy** [comment]
que donne `docker-machine env default` ?

**Comment by AnasGhrab** [comment]
```
Telemeta anas$ docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/anas/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell: 
# eval $(docker-machine env default)
Zeus:Telemeta anas$ docker-compose up
Starting telemeta_broker_1
Starting telemeta_search_1
Starting telemeta_data_1
Starting telemeta_db_1
Starting telemeta_app_1
Starting telemeta_phpmyadmin_1
Starting telemeta_worker_1
Starting telemeta_nginx_1
Attaching to telemeta_broker_1, telemeta_search_1, telemeta_data_1, telemeta_db_1, telemeta_phpmyadmin_1, telemeta_app_1, telemeta_worker_1, telemeta_nginx_1
broker_1      |                 _._                                                  
broker_1      |            _.-``__ ''-._                                             
broker_1      |       _.-``    `.  `_.  ''-._           Redis 3.2.0 (00000000/0) 64 bit
broker_1      |   .-`` .-```.  ```\/    _.,_ ''-._                                   
broker_1      |  (    '      ,       .-`  | `,    )     Running in standalone mode
broker_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
broker_1      |  |    `-._   `._    /     _.-'    |     PID: 1
broker_1      |   `-._    `-._  `-./  _.-'    _.-'                                   
broker_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
broker_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
broker_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
broker_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
broker_1      |  |    `-._`-._        _.-'_.-'    |                                  
broker_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
broker_1      |       `-._    `-.__.-'    _.-'                                       
broker_1      |           `-._        _.-'                                           
broker_1      |               `-.__.-'                                               
broker_1      | 
broker_1      | 1:M 11 May 13:39:29.551 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
broker_1      | 1:M 11 May 13:39:29.551 # Server started, Redis version 3.2.0
broker_1      | 1:M 11 May 13:39:29.551 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
broker_1      | 1:M 11 May 13:39:29.551 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
broker_1      | 1:M 11 May 13:39:29.551 * The server is now ready to accept connections on port 6379
db_1          | 2016-05-11T13:39:30.474106Z 0 [Note] mysqld (mysqld 5.7.12) starting as process 1 ...
db_1          | 2016-05-11T13:39:30.508428Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1          | 2016-05-11T13:39:30.512167Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1          | 2016-05-11T13:39:30.512205Z 0 [Note] InnoDB: Uses event mutexes
db_1          | 2016-05-11T13:39:30.512223Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1          | 2016-05-11T13:39:30.512236Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1          | 2016-05-11T13:39:30.512248Z 0 [Note] InnoDB: Using Linux native AIO
db_1          | 2016-05-11T13:39:30.512490Z 0 [Note] InnoDB: Number of pools: 1
db_1          | 2016-05-11T13:39:30.514846Z 0 [Note] InnoDB: Using CPU crc32 instructions
phpmyadmin_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message
db_1          | 2016-05-11T13:39:30.581859Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
app_1         | waiting for TCP connection to 172.17.0.2
app_1         | 172.17.0.2
app_1         | 172.17.0.4
phpmyadmin_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message
db_1          | 2016-05-11T13:39:30.645295Z 0 [Note] InnoDB: Completed initialization of buffer pool
worker_1      | waiting for TCP connection to 172.17.0.2
app_1         | 172.17.0.4
phpmyadmin_1  | [Wed May 11 13:39:30.842265 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.21 configured -- resuming normal operations
worker_1      | 172.17.0.2
app_1         | 172.17.0.4
db_1          | 2016-05-11T13:39:30.661693Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
phpmyadmin_1  | [Wed May 11 13:39:30.898136 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
app_1         | 172.17.0.4
worker_1      | 172.17.0.5
app_1         | 172.17.0.2
app_1         | 172.17.0.5
app_1         | 172.17.0.5
app_1         | 172.17.0.4
app_1         | 172.17.0.4
app_1         | 172.17.0.5:6379
worker_1      | 172.17.0.5
db_1          | 2016-05-11T13:39:30.669046Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
app_1         | 6379
app_1         | 9200
app_1         | 9300
app_1         | 9200
app_1         | 6379
app_1         | 3306
app_1         | 9300
app_1         | 3306
app_1         | 9200
app_1         | 9300
worker_1      | 172.17.0.2
db_1          | 2016-05-11T13:39:30.738480Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
worker_1      | 172.17.0.5:3306
db_1          | 2016-05-11T13:39:30.744778Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
worker_1      | 6379
db_1          | 2016-05-11T13:39:30.848185Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1          | 2016-05-11T13:39:30.849032Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
worker_1      | 6379
worker_1      | 3306
worker_1      | 3306
db_1          | 2016-05-11T13:39:30.849787Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1          | 2016-05-11T13:39:30.850425Z 0 [Note] InnoDB: Waiting for purge to start
db_1          | 2016-05-11T13:39:30.903459Z 0 [Note] InnoDB: 5.7.12 started; log sequence number 18740477
db_1          | 2016-05-11T13:39:30.910577Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1          | 2016-05-11T13:39:30.920752Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
db_1          | 2016-05-11T13:39:30.921836Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1          | 2016-05-11T13:39:30.921941Z 0 [Note] IPv6 is available.
db_1          | 2016-05-11T13:39:30.922687Z 0 [Note]   - '::' resolves to '::';
db_1          | 2016-05-11T13:39:30.922904Z 0 [Note] Server socket created on IP: '::'.
db_1          | 2016-05-11T13:39:30.931405Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1          | 2016-05-11T13:39:30.944499Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1          | 2016-05-11T13:39:30.986101Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1          | 2016-05-11T13:39:30.988392Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
telemeta_data_1 exited with code 0
db_1          | 2016-05-11T13:39:31.017891Z 0 [Note] InnoDB: Buffer pool(s) load completed at 160511 13:39:31
db_1          | 2016-05-11T13:39:31.019187Z 0 [Note] Event Scheduler: Loaded 0 events
db_1          | 2016-05-11T13:39:31.020214Z 0 [Note] mysqld: ready for connections.
db_1          | Version: '5.7.12'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
search_1      | [2016-05-11 13:39:31,461][INFO ][node                     ] [Wasp] version[1.7.5], pid[1], build[00f95f4/2016-02-02T09:55:30Z]
search_1      | [2016-05-11 13:39:31,465][INFO ][node                     ] [Wasp] initializing ...
search_1      | [2016-05-11 13:39:31,610][INFO ][plugins                  ] [Wasp] loaded [], sites []
search_1      | [2016-05-11 13:39:31,659][INFO ][env                      ] [Wasp] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [177.8gb], net total_space [192.6gb], types [ext4]
search_1      | [2016-05-11 13:39:35,988][INFO ][node                     ] [Wasp] initialized
search_1      | [2016-05-11 13:39:35,988][INFO ][node                     ] [Wasp] starting ...
search_1      | [2016-05-11 13:39:36,201][INFO ][transport                ] [Wasp] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/172.17.0.4:9300]}
search_1      | [2016-05-11 13:39:36,265][INFO ][discovery                ] [Wasp] elasticsearch/YdV40ASmSE6w0Ais6ydP0A
app_1         | 3306...ok
worker_1      | 6379...ok
search_1      | [2016-05-11 13:39:40,111][INFO ][cluster.service          ] [Wasp] new_master [Wasp][YdV40ASmSE6w0Ais6ydP0A][35f62bf052f4][inet[/172.17.0.4:9300]], reason: zen-disco-join (elected_as_master)
search_1      | [2016-05-11 13:39:40,235][INFO ][http                     ] [Wasp] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/172.17.0.4:9200]}
search_1      | [2016-05-11 13:39:40,238][INFO ][node                     ] [Wasp] started
search_1      | [2016-05-11 13:39:40,260][INFO ][gateway                  ] [Wasp] recovered [0] indices into cluster_state
db_1          | 2016-05-11T13:39:44.223574Z 2 [Note] Aborted connection 2 to db: 'telemeta' user: 'telemeta' host: '172.17.0.3' (Got an error reading communication packets)
worker_1      | [2016-05-11 15:39:45,678: WARNING/MainProcess] celery@609462552dc1 ready.
app_1         | Syncing...
app_1         | Creating tables ...
app_1         | Installing custom SQL ...
app_1         | Installing indexes ...
app_1         | Installed 0 object(s) from 0 fixture(s)
app_1         | 
app_1         | Synced:
app_1         |  > django.contrib.auth
app_1         |  > django.contrib.contenttypes
app_1         |  > django.contrib.sessions
app_1         |  > django.contrib.sites
app_1         |  > django.contrib.messages
app_1         |  > suit
app_1         |  > django.contrib.admin
app_1         |  > django.contrib.staticfiles
app_1         |  > south
app_1         |  > sorl.thumbnail
app_1         |  > timezones
app_1         |  > ipauth
app_1         |  > extra_views
app_1         |  > debug_toolbar
app_1         |  > bootstrap3
app_1         |  > rest_framework
app_1         |  > haystack
app_1         |  > djangobower
app_1         |  > djng
app_1         |  > saved_searches
app_1         |  > registration
app_1         | 
app_1         | Not synced (use migrations):
app_1         |  - django_extensions
app_1         |  - telemeta
app_1         |  - timeside.server
app_1         |  - jqchat
app_1         |  - googletools
app_1         |  - djcelery
app_1         | (use ./manage.py migrate to migrate these)
app_1         | Running migrations for django_extensions:
app_1         | - Nothing to migrate.
app_1         |  - Loading initial data for django_extensions.
app_1         | Installed 0 object(s) from 0 fixture(s)
app_1         | Running migrations for telemeta:
app_1         | - Nothing to migrate.
app_1         |  - Loading initial data for telemeta.
app_1         | Installed 0 object(s) from 0 fixture(s)
app_1         | Running migrations for server:
app_1         | - Nothing to migrate.
app_1         |  - Loading initial data for server.
app_1         | Installed 0 object(s) from 0 fixture(s)
app_1         | Running migrations for jqchat:
app_1         | - Nothing to migrate.
app_1         |  - Loading initial data for jqchat.
app_1         | Installed 0 object(s) from 0 fixture(s)
app_1         | Running migrations for googletools:
app_1         | - Nothing to migrate.
app_1         |  - Loading initial data for googletools.
app_1         | Installed 0 object(s) from 0 fixture(s)
app_1         | Running migrations for djcelery:
app_1         | - Nothing to migrate.
app_1         |  - Loading initial data for djcelery.
app_1         | Installed 0 object(s) from 0 fixture(s)
app_1         | bower tablesorter#*         not-cached https://github.com/christianbach/tablesorter.git#*
app_1         | bower tablesorter#*            resolve https://github.com/christianbach/tablesorter.git#*
app_1         | bower loaders#*                 cached https://github.com/Parisson/loaders.git#0.1.1
app_1         | bower loaders#*               validate 0.1.1 against https://github.com/Parisson/loaders.git#*
app_1         | bower ui#*                      cached https://github.com/Parisson/ui.git#0.3.0
app_1         | bower ui#*                    validate 0.3.0 against https://github.com/Parisson/ui.git#*
app_1         | bower jquery#*                  cached https://github.com/jquery/jquery-dist.git#2.2.3
app_1         | bower jquery#*                validate 2.2.3 against https://github.com/jquery/jquery-dist.git#*
app_1         | bower jquery-migrate#~1.2.1     cached https://github.com/appleboy/jquery-migrate.git#1.2.1
app_1         | bower jquery-migrate#~1.2.1   validate 1.2.1 against https://github.com/appleboy/jquery-migrate.git#~1.2.1
app_1         | bower underscore#*              cached https://github.com/jashkenas/underscore.git#1.8.3
app_1         | bower underscore#*            validate 1.8.3 against https://github.com/jashkenas/underscore.git#*
app_1         | bower bootstrap#*               cached https://github.com/twbs/bootstrap.git#3.3.6
app_1         | bower bootstrap#*             validate 3.3.6 against https://github.com/twbs/bootstrap.git#*
app_1         | bower bootstrap-select#1.5.4    cached https://github.com/silviomoreto/bootstrap-select.git#1.5.4
app_1         | bower bootstrap-select#1.5.4  validate 1.5.4 against https://github.com/silviomoreto/bootstrap-select.git#1.5.4
app_1         | bower font-awesome#4.4.0        cached https://github.com/FortAwesome/Font-Awesome.git#4.4.0
app_1         | bower font-awesome#4.4.0      validate 4.4.0 against https://github.com/FortAwesome/Font-Awesome.git#4.4.0
app_1         | bower angular#1.2.26            cached https://github.com/angular/bower-angular.git#1.2.26
app_1         | bower angular#1.2.26          validate 1.2.26 against https://github.com/angular/bower-angular.git#1.2.26
app_1         | bower angular-bootstrap-select#*           cached https://github.com/joaoneto/angular-bootstrap-select.git#0.0.5
app_1         | bower angular-bootstrap-select#*         validate 0.0.5 against https://github.com/joaoneto/angular-bootstrap-select.git#*
app_1         | bower angular-resource#1.2.26              cached https://github.com/angular/bower-angular-resource.git#1.2.26
app_1         | bower angular-resource#1.2.26            validate 1.2.26 against https://github.com/angular/bower-angular-resource.git#1.2.26
app_1         | bower raphael#*                            cached https://github.com/DmitryBaranovskiy/raphael.git#2.2.0
app_1         | bower raphael#*                          validate 2.2.0 against https://github.com/DmitryBaranovskiy/raphael.git#*
app_1         | bower soundmanager#V2.97a.20150601         cached https://github.com/scottschiller/SoundManager2.git#V2.97a.20150601
app_1         | bower soundmanager#V2.97a.20150601       validate V2.97a.20150601 against https://github.com/scottschiller/SoundManager2.git#V2.97a.20150601
app_1         | bower jquery-ui#*                          cached https://github.com/components/jqueryui.git#1.11.4
app_1         | bower jquery-ui#*                        validate 1.11.4 against https://github.com/components/jqueryui.git#*
app_1         | bower video.js#*                           cached https://github.com/videojs/video.js.git#5.10.1
app_1         | bower video.js#*                         validate 5.10.1 against https://github.com/videojs/video.js.git#*
app_1         | bower sass-bootstrap-glyphicons#*          cached https://github.com/greaterweb/sass-bootstrap-glyphicons.git#1.0.0
app_1         | bower sass-bootstrap-glyphicons#*        validate 1.0.0 against https://github.com/greaterweb/sass-bootstrap-glyphicons.git#*
app_1         | bower jquery#1.9.1 - 2                     cached https://github.com/jquery/jquery-dist.git#2.2.3
app_1         | bower jquery#1.9.1 - 2                   validate 2.2.3 against https://github.com/jquery/jquery-dist.git#1.9.1 - 2
app_1         | bower jquery#>=1.6                         cached https://github.com/jquery/jquery-dist.git#2.2.3
app_1         | bower jquery#>=1.6                       validate 2.2.3 against https://github.com/jquery/jquery-dist.git#>=1.6
app_1         | bower tablesorter#*                      checkout master
app_1         | bower tablesorter#*                      resolved https://github.com/christianbach/tablesorter.git#774576308e
app_1         | 
app_1         | 0 static files copied to '/srv/static', 1845 unmodified.
app_1         | scripts/app.sh: line 45: [: =: unary operator expected
app_1         | *** Starting uWSGI 2.0.12 (64bit) on [Wed May 11 13:40:11 2016] ***
app_1         | compiled with version: 4.9.2 on 19 March 2016 10:08:28
app_1         | os: Linux-4.4.8-boot2docker #1 SMP Mon Apr 25 21:57:27 UTC 2016
app_1         | nodename: f468b4ae050d
app_1         | machine: x86_64
app_1         | clock source: unix
app_1         | detected number of CPU cores: 1
app_1         | current working directory: /srv/app
app_1         | detected binary path: /opt/miniconda/bin/uwsgi
app_1         | !!! no internal routing support, rebuild with pcre support !!!
app_1         | setgid() to 33
app_1         | setuid() to 33
app_1         | chdir() to /srv/app
app_1         | your processes number limit is 1048576
app_1         | your memory page size is 4096 bytes
app_1         | detected max file descriptor number: 1048576
app_1         | lock engine: pthread robust mutexes
app_1         | thunder lock: disabled (you can enable it with --thunder-lock)
app_1         | uwsgi socket 0 bound to TCP address :8000 fd 3
app_1         | Python version: 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
app_1         | Python main interpreter initialized at 0x22b1e40
app_1         | python threads support enabled
app_1         | your server socket listen backlog is limited to 100 connections
app_1         | your mercy for graceful operations on workers is 60 seconds
app_1         | mapped 1304064 bytes (1273 KB) for 64 cores
app_1         | *** Operational MODE: preforking+threaded ***
app_1         | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x22b1e40 pid: 119 (default app)
app_1         | *** uWSGI is running in multiple interpreter mode ***
app_1         | spawned uWSGI master process (pid: 119)
app_1         | spawned uWSGI worker 1 (pid: 126, cores: 8)
app_1         | spawned uWSGI worker 2 (pid: 127, cores: 8)
app_1         | spawned uWSGI worker 3 (pid: 128, cores: 8)
app_1         | spawned uWSGI worker 4 (pid: 129, cores: 8)
app_1         | spawned uWSGI worker 5 (pid: 130, cores: 8)
app_1         | spawned uWSGI worker 6 (pid: 147, cores: 8)
app_1         | spawned uWSGI worker 7 (pid: 148, cores: 8)
app_1         | spawned uWSGI worker 8 (pid: 149, cores: 8)
app_1         | Python auto-reloader enabled
app_1         | Indexing 0 items
app_1         | Indexing 0 collections
app_1         | Indexing 0 corpus
app_1         | Indexing 0 fonds
db_1          | 2016-05-11T13:40:16.593776Z 13 [Note] Aborted connection 13 to db: 'telemeta' user: 'telemeta' host: '172.17.0.3' (Got an error reading communication packets)
app_1         | Traceback (most recent call last):
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
app_1         |     self.load_middleware()
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
app_1         |     mw_instance = mw_class()
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
app_1         |     for url_pattern in get_resolver(None).url_patterns:
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
app_1         |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
app_1         |     self._urlconf_module = import_module(self.urlconf_name)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
app_1         |     __import__(name)
app_1         |   File "./urls.py", line 30, in <module>
app_1         |     (r'^', include('telemeta.urls')),
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
app_1         |     urlconf_module = import_module(urlconf_module)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
app_1         |     __import__(name)
app_1         |   File "/srv/src/telemeta/telemeta/urls.py", line 28, in <module>
app_1         |     from telemeta.views import *
app_1         |   File "/srv/src/telemeta/telemeta/views/__init__.py", line 21, in <module>
app_1         |     from telemeta.views.home import *
app_1         |   File "/srv/src/telemeta/telemeta/views/home.py", line 24, in <module>
app_1         |     from telemeta.views.core import *
app_1         |   File "/srv/src/telemeta/telemeta/views/core.py", line 85, in <module>
app_1         |     class TelemetaBaseMixin(object):
app_1         |   File "/srv/src/telemeta/telemeta/views/core.py", line 89, in TelemetaBaseMixin
app_1         |     cache_data = TelemetaCache(getattr(settings, 'TELEMETA_DATA_CACHE_DIR', CACHE_DIR))
app_1         |   File "/srv/src/telemeta/telemeta/cache.py", line 35, in __init__
app_1         |     os.makedirs(dir)
app_1         |   File "/opt/miniconda/lib/python2.7/os.py", line 150, in makedirs
app_1         |     makedirs(head, mode)
app_1         |   File "/opt/miniconda/lib/python2.7/os.py", line 157, in makedirs
app_1         |     mkdir(name, mode)
app_1         | OSError: [Errno 13] Permission denied: '/srv/media/cache'
app_1         | [pid: 149|app: 0|req: 1/1] 192.168.99.1 () {40 vars in 701 bytes} [Wed May 11 15:41:09 2016] GET / => generated 0 bytes in 4512 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
app_1         | Traceback (most recent call last):
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
app_1         |     self.load_middleware()
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
app_1         |     mw_instance = mw_class()
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
app_1         |     for url_pattern in get_resolver(None).url_patterns:
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
app_1         |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
app_1         |     self._urlconf_module = import_module(self.urlconf_name)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
app_1         |     __import__(name)
app_1         |   File "urls.py", line 30, in <module>
app_1         |     (r'^', include('telemeta.urls')),
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
app_1         |     urlconf_module = import_module(urlconf_module)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
app_1         |     __import__(name)
app_1         |   File "/srv/src/telemeta/telemeta/urls.py", line 28, in <module>
app_1         |     from telemeta.views import *
app_1         |   File "/srv/src/telemeta/telemeta/views/__init__.py", line 21, in <module>
app_1         |     from telemeta.views.home import *
app_1         |   File "/srv/src/telemeta/telemeta/views/home.py", line 24, in <module>
app_1         |     from telemeta.views.core import *
app_1         |   File "/srv/src/telemeta/telemeta/views/core.py", line 85, in <module>
app_1         |     class TelemetaBaseMixin(object):
app_1         |   File "/srv/src/telemeta/telemeta/views/core.py", line 89, in TelemetaBaseMixin
app_1         |     cache_data = TelemetaCache(getattr(settings, 'TELEMETA_DATA_CACHE_DIR', CACHE_DIR))
app_1         |   File "/srv/src/telemeta/telemeta/cache.py", line 35, in __init__
app_1         |     os.makedirs(dir)
app_1         |   File "/opt/miniconda/lib/python2.7/os.py", line 150, in makedirs
app_1         |     makedirs(head, mode)
app_1         |   File "/opt/miniconda/lib/python2.7/os.py", line 157, in makedirs
app_1         |     mkdir(name, mode)
app_1         | OSError: [Errno 13] Permission denied: '/srv/media/cache'
app_1         | [pid: 149|app: 0|req: 2/2] 192.168.99.1 () {40 vars in 660 bytes} [Wed May 11 15:41:14 2016] GET /favicon.ico => generated 0 bytes in 47 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 7)
```

**Comment by yomguy** [comment]
please pull dev to test the fox on OSX, thanks Anas !

**Comment by AnasGhrab** [comment]
Yes it works now ! For the first time, Telemeta on my mac ! Thanks :)

**Comment by yomguy** [comment]
Great news!
