### ISSUE TITLE
Problem with Docker-compose on MacOS

### ISSUE THREAD

**Issue by lluc** [Parisson/Telemeta#146]
Made a "_docker-compose build_" and a "_docker-compose up_".

Telemeta doesn't woks properly  --> 502 Bad Gateway.
It seems that there's a problem with MySQL. Perharps its installation or parameters ...   ... or just _permissions_ ?
Here is a part of the terminal's output : 

``````
Creating telemeta_broker_1
Creating telemeta_search_1
Creating telemeta_data_1
Creating telemeta_db_1
Creating telemeta_phpmyadmin_1
Creating telemeta_app_1
Creating telemeta_worker_1
Creating telemeta_nginx_1
Attaching to telemeta_broker_1, telemeta_search_1, telemeta_data_1, telemeta_db_1,
telemeta_phpmyadmin_1, telemeta_app_1, telemeta_worker_1, telemeta_nginx_1
broker_1 | 1:C 14 Oct 13:41:42.097 # Warning: no config file specified, using the default
config. In order to specify a config file use redis-server /path/to/redis.conf
broker_1 | _._
db_1 | Initializing database
broker_1 | _.-``__ ''-._
broker_1 | _.-`` `. `_. ''-._ Redis 3.2.4 (00000000/0) 64 bit
db_1 | mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission
denied)
broker_1 | .-`` .-```. ```\/ _.,_ ''-._
telemeta_data_1 exited with code 0
broker_1 | ( ' , .-` | `, ) Running in standalone mode
broker_1 | |`-._`-...-` __...-.``-._|'` _.-'| Port: 6379
broker_1 | | `-._ `._ / _.-' | PID: 1
broker_1 | `-._ `-._ `-./ _.-' _.-'
broker_1 | |`-._`-._ `-.__.-' _.-'_.-'|
broker_1 | | `-._`-._ _.-'_.-' | http://redis.io
broker_1 | `-._ `-._`-.__.-'_.-' _.-'
broker_1 | |`-._`-._ `-.__.-' _.-'_.-'|
db_1 | 2016-10-14T13:41:43.190790Z 0 [Warning] TIMESTAMP with implicit DEFAULT
value is deprecated. Please use --explicit_defaults_for_timestamp server option (see
documentation for more details).
broker_1 | | `-._`-._ _.-'_.-' |
db_1 | 2016-10-14T13:41:43.218974Z 0 [ERROR] --initialize specified but the data directory
exists and is not writable. Aborting.
phpmyadmin_1 | AH00558: apache2: Could not reliably determine the server's fully qualified
domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
broker_1 | `-._ `-._`-.__.-'_.-' _.-'
db_1 | 2016-10-14T13:41:43.219228Z 0 [ERROR] Aborting
broker_1 | `-._ `-.__.-' _.-'
db_1 |
broker_1 | `-._ _.-'
broker_1 | `-.__.-'
broker_1 |
phpmyadmin_1 | AH00558: apache2: Could not reliably determine the server's fully qualified
domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
broker_1 | 1:M 14 Oct 13:41:42.101 # WARNING: The TCP backlog setting of 511 cannot be
enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
phpmyadmin_1 | [Fri Oct 14 13:41:43.942002 2016] [mpm_prefork:notice] [pid 1] AH00163:
Apache/2.4.10 (Debian) PHP/5.6.26 configured -- resuming normal operations
broker_1 | 1:M 14 Oct 13:41:42.101 # Server started, Redis version 3.2.4
broker_1 | 1:M 14 Oct 13:41:42.101 # WARNING overcommit_memory is set to 0! Background
save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to
/etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to
take effect.
telemeta_db_1 exited with code 1
worker_1 | waiting for TCP connection to 172.17.0.2
worker_1 | 172.17.0.2
worker_1 | 172.17.0.2:6379

worker_1 | 6379

search_1 | [2016-10-14 13:41:44,949][INFO ][node ] [Adonis] version[1.7.5],

pid[1], build[00f95f4/2016-02-02T09:55:30Z]

search_1 | [2016-10-14 13:41:44,951][INFO ][node ] [Adonis] initializing ...

search_1 | [2016-10-14 13:41:45,156][INFO ][plugins ] [Adonis] loaded [], sites []

app_1 | waiting for TCP connection to 172.17.0.2

app_1 | 172.17.0.2

app_1 | 172.17.0.4

app_1 | 172.17.0.4

app_1 | 172.17.0.4

app_1 | 172.17.0.4

app_1 | 172.17.0.2

app_1 | 172.17.0.3

app_1 | 172.17.0.3

app_1 | 172.17.0.4

app_1 | 172.17.0.4

app_1 | 172.17.0.3:6379

app_1 | 6379

app_1 | 9200

app_1 | 9300

app_1 | 9200

app_1 | 6379

app_1 | 3306

app_1 | 9300

app_1 | 3306

app_1 | 9200

app_1 | 9300

search_1 | [2016-10-14 13:41:45,239][INFO ][env ] [Adonis] using [1] data paths,

mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [178gb], net total_space

[192.6gb], types [ext4]

search_1 | [2016-10-14 13:41:50,576][INFO ][node ] [Adonis] initialized

search_1 | [2016-10-14 13:41:50,583][INFO ][node ] [Adonis] starting ...

search_1 | [2016-10-14 13:41:51,115][INFO ][transport ] [Adonis] bound_address

{inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/172.17.0.4:9300]}

search_1 | [2016-10-14 13:41:51,367][INFO ][discovery ] [Adonis]

elasticsearch/OGEHypz2RiGMzy29Rtg3CQ

search_1 | [2016-10-14 13:41:55,287][INFO ][cluster.service ] [Adonis] new_master

[Adonis][OGEHypz2RiGMzy29Rtg3CQ][316f0f0344a2][inet[/172.17.0.4:9300]], reason: zen-disco-
join (elected_as_master)

search_1 | [2016-10-14 13:41:55,400][INFO ][http ] [Adonis] bound_address

{inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/172.17.0.4:9200]}

search_1 | [2016-10-14 13:41:55,410][INFO ][node ] [Adonis] started

worker_1 | 6379...ok

app_1 | 3306...ok

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...retrying

app_1 | error connecting to DB...

app_1 | ...exiting

app_1 | Traceback (most recent call last):

app_1 | File "/srv/app/manage.py", line 7, in <module>

app_1 | execute_from_command_line(sys.argv)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/__init__.py", line 399, in execute_from_command_line

app_1 | utility.execute()

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/__init__.py", line 392, in execute

app_1 | self.fetch_command(subcommand).run_from_argv(self.argv)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/base.py", line 242, in run_from_argv

app_1 | self.execute(*args, **options.__dict__)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/base.py", line 285, in execute

app_1 | output = self.handle(*args, **options)

app_1 | File "/srv/src/timeside/timeside/server/management/commands/wait-for-db.py", line

21, in handle

app_1 | c = db_conn.cursor()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 162, in cursor

app_1 | cursor = util.CursorWrapper(self._cursor(), self)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 132, in _cursor

app_1 | self.ensure_connection()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 127, in ensure_connection

app_1 | self.connect()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/utils.py", line 99, in

__exit__

app_1 | six.reraise(dj_exc_type, dj_exc_value, traceback)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 127, in ensure_connection

app_1 | self.connect()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 115, in connect

app_1 | self.connection = self.get_new_connection(conn_params)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/db/backends/mysql/base.py", line 435, in get_new_connection

app_1 | conn = Database.connect(**conn_params)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in

Connect

app_1 | return Connection(*args, **kwargs)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/connections.py", line

193, in __init__

app_1 | super(Connection, self).__init__(*args, **kwargs2)

app_1 | django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'db'

(111)")

app_1 | Syncing...

app_1 | Traceback (most recent call last):

app_1 | File "/srv/app/manage.py", line 7, in <module>

app_1 | execute_from_command_line(sys.argv)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/__init__.py", line 399, in execute_from_command_line

app_1 | utility.execute()

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/__init__.py", line 392, in execute

app_1 | self.fetch_command(subcommand).run_from_argv(self.argv)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/base.py", line 242, in run_from_argv

app_1 | self.execute(*args, **options.__dict__)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/base.py", line 285, in execute

app_1 | output = self.handle(*args, **options)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/base.py", line 415, in handle

app_1 | return self.handle_noargs(**options)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/south/management/commands/syncdb.py", line 89, in handle_noargs

app_1 | db.connection_init()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/south/db/mysql.py", line 183, in

connection_init

app_1 | cursor = self._get_connection().cursor()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 162, in cursor

app_1 | cursor = util.CursorWrapper(self._cursor(), self)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 132, in _cursor

app_1 | self.ensure_connection()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 127, in ensure_connection

app_1 | self.connect()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/utils.py", line 99, in

__exit__

app_1 | six.reraise(dj_exc_type, dj_exc_value, traceback)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 127, in ensure_connection

app_1 | self.connect()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 115, in connect

app_1 | self.connection = self.get_new_connection(conn_params)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/db/backends/mysql/base.py", line 435, in get_new_connection

app_1 | conn = Database.connect(**conn_params)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in

Connect

app_1 | return Connection(*args, **kwargs)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/connections.py", line

193, in __init__

app_1 | super(Connection, self).__init__(*args, **kwargs2)

app_1 | django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'db'

(111)")

app_1 | Traceback (most recent call last):

app_1 | File "/srv/app/manage.py", line 7, in <module>

app_1 | execute_from_command_line(sys.argv)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/__init__.py", line 399, in execute_from_command_line

app_1 | utility.execute()

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/__init__.py", line 392, in execute

app_1 | self.fetch_command(subcommand).run_from_argv(self.argv)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/base.py", line 242, in run_from_argv

app_1 | self.execute(*args, **options.__dict__)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/core/management/base.py", line 285, in execute

app_1 | output = self.handle(*args, **options)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/south/management/commands/migrate.py", line 111, in handle

app_1 | ignore_ghosts = ignore_ghosts,

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/south/migration/__init__.py", line

200, in migrate_app

app_1 | applied_all = check_migration_histories(applied_all, delete_ghosts,

ignore_ghosts)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/south/migration/__init__.py", line

79, in check_migration_histories

app_1 | for h in histories:

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/query.py", line

96, in __iter__

app_1 | self._fetch_all()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/query.py", line

857, in _fetch_all

app_1 | self._result_cache = list(self.iterator())

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/query.py", line

220, in iterator

app_1 | for row in compiler.results_iter():

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/sql/compiler.py",

line 713, in results_iter

app_1 | for rows in self.execute_sql(MULTI):

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/sql/compiler.py",

line 785, in execute_sql

app_1 | cursor = self.connection.cursor()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 162, in cursor

app_1 | cursor = util.CursorWrapper(self._cursor(), self)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 132, in _cursor

app_1 | self.ensure_connection()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 127, in ensure_connection

app_1 | self.connect()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/utils.py", line 99, in

__exit__

app_1 | six.reraise(dj_exc_type, dj_exc_value, traceback)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 127, in ensure_connection

app_1 | self.connect()

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/__init__.py",

line 115, in connect

app_1 | self.connection = self.get_new_connection(conn_params)

app_1 | File "/opt/miniconda/lib/python2.7/site-
packages/django/db/backends/mysql/base.py", line 435, in get_new_connection

app_1 | conn = Database.connect(**conn_params)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in

Connect

app_1 | return Connection(*args, **kwargs)

app_1 | File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/connections.py", line

193, in __init__

app_1 | super(Connection, self).__init__(*args, **kwargs2)

app_1 | django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'db'
`
``````

**Comment by yomguy** [comment]
Hi,
The docker version of MySQL induces a bug on MacOS against data directory access, please try again after commenting this line  https://github.com/Parisson/Telemeta/blob/master/docker-compose.yml#L38
Cheers

**Comment by lluc** [comment]
OK, the script seems run more far away.
BUT, it doesn't serve when the web crawler ask him on the 8000 port. :-(

**Comment by thomasfillon** [comment]
Bonjour Luc,

Could you please post the new terminal output.

**Comment by lluc** [comment]
N.B : It's the terminal output of my customer. His computer runs on MacOS.

```
 detected max file descriptor number: 1048576
app_1         | lock engine: pthread robust mutexes
app_1         | thunder lock: disabled (you can enable it with --thunder-lock)
app_1         | uwsgi socket 0 bound to TCP address :8000 fd 3
app_1         | Python version: 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
app_1         | Python main interpreter initialized at 0x12de320
app_1         | python threads support enabled
app_1         | your server socket listen backlog is limited to 100 connections
app_1         | your mercy for graceful operations on workers is 60 seconds
app_1         | mapped 1304064 bytes (1273 KB) for 64 cores
app_1         | *** Operational MODE: preforking+threaded ***
app_1         | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x12de320 pid: 273 (default app)
app_1         | *** uWSGI is running in multiple interpreter mode ***
app_1         | spawned uWSGI master process (pid: 273)
app_1         | spawned uWSGI worker 1 (pid: 276, cores: 8)
app_1         | spawned uWSGI worker 2 (pid: 277, cores: 8)
app_1         | spawned uWSGI worker 3 (pid: 278, cores: 8)
app_1         | spawned uWSGI worker 4 (pid: 279, cores: 8)
app_1         | spawned uWSGI worker 5 (pid: 280, cores: 8)
app_1         | spawned uWSGI worker 6 (pid: 305, cores: 8)
app_1         | spawned uWSGI worker 7 (pid: 314, cores: 8)
app_1         | spawned uWSGI worker 8 (pid: 315, cores: 8)
broker_1      | 1:M 13 Oct 19:58:33.750 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
broker_1      | 1:M 13 Oct 19:58:33.750 * The server is now ready to accept connections on port 6379
broker_1      | 1:M 13 Oct 20:35:21.783 * 100 changes in 300 seconds. Saving...
broker_1      | 1:M 13 Oct 20:35:21.785 * Background saving started by pid 12
broker_1      | 12:C 13 Oct 20:35:21.790 * DB saved on disk
broker_1      | 12:C 13 Oct 20:35:21.790 * RDB: 6 MB of memory used by copy-on-write
broker_1      | 1:M 13 Oct 20:35:21.888 * Background saving terminated with success
broker_1      | 1:M 13 Oct 21:17:02.200 * 100 changes in 300 seconds. Saving...
broker_1      | 1:M 13 Oct 21:17:02.200 * Background saving started by pid 13
broker_1      | 13:C 13 Oct 21:17:02.208 * DB saved on disk
broker_1      | 13:C 13 Oct 21:17:02.209 * RDB: 6 MB of memory used by copy-on-write
broker_1      | 1:M 13 Oct 21:17:02.301 * Background saving terminated with success
broker_1      | 1:M 13 Oct 21:58:42.398 * 100 changes in 300 seconds. Saving...
broker_1      | 1:M 13 Oct 21:58:42.399 * Background saving started by pid 14
```
Etc, etc ... ... and so on ...

**Comment by lluc** [comment]
OK.
After using the right IP address (192.168.99.100), the server respond to web client.  :-)
BUT, there's another problem, about the cache.
Here's my terminal output : 

```
app_1         | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1fff320 pid: 140 (default app)
app_1         | *** uWSGI is running in multiple interpreter mode ***
app_1         | spawned uWSGI master process (pid: 140)
app_1         | spawned uWSGI worker 1 (pid: 143, cores: 8)
app_1         | spawned uWSGI worker 2 (pid: 144, cores: 8)
app_1         | spawned uWSGI worker 3 (pid: 145, cores: 8)
app_1         | spawned uWSGI worker 4 (pid: 146, cores: 8)
app_1         | spawned uWSGI worker 5 (pid: 147, cores: 8)
app_1         | spawned uWSGI worker 6 (pid: 148, cores: 8)
app_1         | spawned uWSGI worker 7 (pid: 149, cores: 8)
app_1         | spawned uWSGI worker 8 (pid: 150, cores: 8)
telemeta_data_1 exited with code 0
telemeta_data_1 exited with code 0
app_1         | Python auto-reloader enabled
app_1         | Traceback (most recent call last):
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
app_1         |     self.load_middleware()
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
app_1         |     mw_instance = mw_class()
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
app_1         |     for url_pattern in get_resolver(None).url_patterns:
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
app_1         |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
app_1         |     self._urlconf_module = import_module(self.urlconf_name)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
app_1         |     __import__(name)
app_1         |   File "./urls.py", line 30, in <module>
app_1         |     (r'^', include('telemeta.urls')),
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
app_1         |     urlconf_module = import_module(urlconf_module)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
app_1         |     __import__(name)
app_1         |   File "/srv/src/telemeta/telemeta/urls.py", line 28, in <module>
app_1         |     from telemeta.views import *
app_1         |   File "/srv/src/telemeta/telemeta/views/__init__.py", line 21, in <module>
app_1         |     from telemeta.views.home import *
app_1         |   File "/srv/src/telemeta/telemeta/views/home.py", line 24, in <module>
app_1         |     from telemeta.views.core import *
app_1         |   File "/srv/src/telemeta/telemeta/views/core.py", line 85, in <module>
app_1         |     class TelemetaBaseMixin(object):
app_1         |   File "/srv/src/telemeta/telemeta/views/core.py", line 89, in TelemetaBaseMixin
app_1         |     cache_data = TelemetaCache(getattr(settings, 'TELEMETA_DATA_CACHE_DIR', CACHE_DIR))
app_1         |   File "/srv/src/telemeta/telemeta/cache.py", line 35, in __init__
app_1         |     os.makedirs(dir)
```
I'm guessing that's peharps a problem of rights access ? ...

**Comment by AnasGhrab** [comment]
Everything works well for me now with the last version of Docker on OS X (https://docs.docker.com/docker-for-mac/) : 

```
Docker version 1.13.1, build 092cba3
```
