### ISSUE TITLE
TimeSide not found using docker

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#160]
With the master branch, at least os X, when I do ```docker-compose up```, I get : 

```
search_1      | [2017-03-24 08:14:46,501][INFO ][gateway                  ] [Infinity] recovered [0] indices into cluster_state
app_1         | 3306...ok
app_1         | Traceback (most recent call last):
app_1         |   File "/srv/app/manage.py", line 7, in <module>
app_1         |     execute_from_command_line(sys.argv)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
app_1         |     utility.execute()
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
app_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
app_1         |     self.execute(*args, **options.__dict__)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 280, in execute
app_1         |     translation.activate('en-us')
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 130, in activate
app_1         |     return _trans.activate(language)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 188, in activate
app_1         |     _active.value = translation(language)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
app_1         |     default_translation = _fetch(settings.LANGUAGE_CODE)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
app_1         |     app = import_module(appname)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
app_1         |     __import__(name)
app_1         | ImportError: No module named timeside.server
```

and then

```
app_1         | django.core.exceptions.ImproperlyConfigured: ImportError timeside.player: No module named timeside.player
```

and

```
app_1         | ImportError: No module named timeside.core
```

I have tried that with fresh images pull...

It was working some weeks ago...

**Comment by thomasfillon** [comment]
Hi Anas

Could you please give the output of the following command: `docker-compose run app ls /srv/src/timeside` ?

**Comment by AnasGhrab** [comment]
Oups.. I think it is because I forgot the --recursive option with git clone..

**Comment by thomasfillon** [comment]
ok fine. Thanks for your feedback.
