### ISSUE TITLE
Goto Django 1.8

### ISSUE THREAD

**Issue by thomasfillon** [Parisson/Telemeta#172]
this issue is a first step towards Django 1.9 in  #99

**Comment by lluc** [comment]
On the server ( Univ-Poitiers ), there is a problem with this command : 
`docker-compose -f docker-compose.yml -f env/dev.yml run app python manage.py makemigrations`

Answer is : 
`Starting univpoitiers_data_1
Unknown command: 'makemigrations'
Type 'manage.py help' for usage.`

Strange ? ....

**Comment by thomasfillon** [comment]
Hi @lluc 

`makemigrations` command was introduced in Django 1.7 with the switch from south to built-in management for migrations.
This error seems to append because you are still using an old version of Telemeta.
Did you update docker images and build properly ?

**Comment by lluc** [comment]
OK.
Perharps my previous `Git pull` was not clean.
So, I made one `Git pull` again, and build the container (  `docker-compose -f docker-compose.yml -f env/dev.yml build` )
But when I do `docker-compose -f docker-compose.yml -f env/dev.yml run app python manage.py migrate server zero`, I receive that : 

```
Traceback (most recent call last):

  File "manage.py", line 7, in <module>    execute_from_command_line(sys.argv)

  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line    utility.execute()

  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute       django.setup()

  File "/opt/miniconda/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)

  File "/opt/miniconda/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)

  File "/opt/miniconda/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)

  File "/opt/miniconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)

  File "/srv/src/timeside/timeside/server/models.py", line 43, in <module>
    import jsonfield
```

Perharps _TimeSide_ ? ...

**Comment by thomasfillon** [comment]
Could you please post the end of the error message here and post the whole error message in  [Framabin](https://framabin.org/) or an equivalent service.

**Comment by lluc** [comment]
Here it is : https://framabin.org/?5d914b9c41f37807#MoNzZz6jsFPAK9E07IpUZe+YyvLOHD/ycR9OgIRl1a4=

**Comment by thomasfillon** [comment]
Did you pull `parisson/timeside:latest-dev` ?

**Comment by thomasfillon** [comment]
I mean  `docker pull `.

**Comment by lluc** [comment]
No, just `git submodule update --init --recursive`

**Comment by thomasfillon** [comment]
Please do as indicated in the pad. You need to update this docker image which seems to be outdated on this server.

**Comment by lluc** [comment]
Oups !
Thanks you Thomas, I missed this line ( _docker pull ..._ ) when I've mixed my documentations and the pad.

**Comment by thomasfillon** [comment]
No problem.
Please let me know if everything goes fine now.
