### ISSUE TITLE
Upgrade to 1.7 problem

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#209]
When doing the commands : 

```
git pull origin master
git submodule update --init --remote
docker-compose run app /srv/app/bin/upgrade_from_1.6_to_1.7.sh
```

I got : 

````
Pulling app (parisson/telemeta:1.7)...
1.7: Pulling from parisson/telemeta
d660b1f15b9b: Pull complete
f33ce37f90cd: Pull complete
b85da5b26f53: Pull complete
6efd0586f688: Pull complete
99a9afb9f129: Pull complete
bf93be073410: Pull complete
60d590650d0f: Pull complete
ec87eece40d4: Pull complete
5d7cd36f4086: Pull complete
82027c938177: Pull complete
f9ec2f4e45ba: Pull complete
7eda1b94549e: Pull complete
6f92ac43df22: Pull complete
6df41bbf717e: Pull complete
278b8e5c3daa: Pull complete
6a6b6821e147: Pull complete
514b72810f4c: Pull complete
e5b84e7ade6c: Pull complete
83361ad88c2d: Pull complete
b1348f65fd50: Pull complete
a8e6060de5e1: Pull complete
816a19d76252: Pull complete
9e7123622f57: Pull complete
86cb04fce29a: Pull complete
5436313a72c3: Pull complete
7d698be3e2d4: Pull complete
70db95cf177d: Pull complete
e4fff62aecaa: Pull complete
3bb2d98c7daa: Pull complete
4df4f070f214: Pull complete
33b0194b3720: Pull complete
d34454947e20: Pull complete
Digest: sha256:372940a5db18a63754e748a4e54360bff628ddbdf9d1489ec4fcfa224e054105
Status: Downloaded newer image for parisson/telemeta:1.7
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/opt/miniconda/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/miniconda/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/opt/miniconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named djng
````

**Comment by yomguy** [comment]
Hi @AnasGhrab it is fixed in 1.7.1, please upgrade : `git pull; docker-compose pull`
