### ISSUE TITLE
Fresh installation problem

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#217]
I can't make an install of the last version on Debian 9. I get : django.db.utils.ProgrammingError: (1146, "Table 'telemeta.auth_user' doesn't exist")

It seems that it didn't make the first migrate.

```
db_1      | 2019-07-31T23:12:12.454621Z 0 [Note] Giving 0 client threads a chance to die gracefully
db_1      | 2019-07-31T23:12:12.454655Z 0 [Note] Shutting down slave threads
db_1      | 2019-07-31T23:12:12.454664Z 0 [Note] Forcefully disconnecting 0 remaining clients
db_1      | 2019-07-31T23:12:12.454673Z 0 [Note] Event Scheduler: Purging the queue. 0 events
db_1      | 2019-07-31T23:12:12.454730Z 0 [Note] Binlog end
db_1      | 2019-07-31T23:12:12.455610Z 0 [Note] Shutting down plugin 'ngram'
db_1      | 2019-07-31T23:12:12.455630Z 0 [Note] Shutting down plugin 'partition'
db_1      | 2019-07-31T23:12:12.455641Z 0 [Note] Shutting down plugin 'BLACKHOLE'
db_1      | 2019-07-31T23:12:12.455649Z 0 [Note] Shutting down plugin 'ARCHIVE'
db_1      | 2019-07-31T23:12:12.455655Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
db_1      | 2019-07-31T23:12:12.455692Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
db_1      | 2019-07-31T23:12:12.455706Z 0 [Note] Shutting down plugin 'MyISAM'
db_1      | 2019-07-31T23:12:12.455739Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
db_1      | 2019-07-31T23:12:12.455748Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
db_1      | 2019-07-31T23:12:12.455753Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
db_1      | 2019-07-31T23:12:12.455759Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
db_1      | 2019-07-31T23:12:12.455764Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
db_1      | 2019-07-31T23:12:12.455769Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
db_1      | 2019-07-31T23:12:12.455774Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
db_1      | 2019-07-31T23:12:12.455780Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
db_1      | 2019-07-31T23:12:12.455785Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
db_1      | 2019-07-31T23:12:12.455790Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
db_1      | 2019-07-31T23:12:12.455795Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
db_1      | 2019-07-31T23:12:12.455815Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
db_1      | 2019-07-31T23:12:12.455821Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
db_1      | 2019-07-31T23:12:12.455826Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
db_1      | 2019-07-31T23:12:12.455831Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
db_1      | 2019-07-31T23:12:12.455836Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
db_1      | 2019-07-31T23:12:12.455842Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
db_1      | 2019-07-31T23:12:12.455847Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
db_1      | 2019-07-31T23:12:12.455853Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
db_1      | 2019-07-31T23:12:12.455858Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
db_1      | 2019-07-31T23:12:12.455864Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
db_1      | 2019-07-31T23:12:12.455869Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
db_1      | 2019-07-31T23:12:12.455874Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
db_1      | 2019-07-31T23:12:12.455892Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
db_1      | 2019-07-31T23:12:12.455898Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
db_1      | 2019-07-31T23:12:12.455903Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
db_1      | 2019-07-31T23:12:12.455908Z 0 [Note] Shutting down plugin 'INNODB_CMP'
db_1      | 2019-07-31T23:12:12.455913Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
db_1      | 2019-07-31T23:12:12.455918Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
db_1      | 2019-07-31T23:12:12.455924Z 0 [Note] Shutting down plugin 'INNODB_TRX'
db_1      | 2019-07-31T23:12:12.455929Z 0 [Note] Shutting down plugin 'InnoDB'
db_1      | 2019-07-31T23:12:12.456007Z 0 [Note] InnoDB: FTS optimize thread exiting.
db_1      | 2019-07-31T23:12:12.456144Z 0 [Note] InnoDB: Starting shutdown...
db_1      | 2019-07-31T23:12:12.556363Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1      | 2019-07-31T23:12:12.556688Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 190731 23:12:12
app_1     | Traceback (most recent call last):
app_1     |   File "/srv/app/manage.py", line 7, in <module>
app_1     |     execute_from_command_line(sys.argv)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
app_1     |     utility.execute()
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
app_1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
app_1     |     self.execute(*args, **cmd_options)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
app_1     |     self.check()
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 482, in check
app_1     |     include_deployment_checks=include_deployment_checks,
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
app_1     |     new_errors = check(app_configs=app_configs)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
app_1     |     errors.extend(model.check(**kwargs))
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/base.py", line 1205, in check
app_1     |     errors.extend(cls._check_fields(**kwargs))
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/base.py", line 1282, in _check_fields
app_1     |     errors.extend(field.check(**kwargs))
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 934, in check
app_1     |     errors = super(AutoField, self).check(**kwargs)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 207, in check
app_1     |     errors.extend(self._check_backend_specific_checks(**kwargs))
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 306, in _check_backend_specific_checks
app_1     |     return connection.validation.check_field(self, **kwargs)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 18, in check_field
app_1     |     field_type = field.db_type(connection)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 614, in db_type
app_1     |     return connection.data_types[self.get_internal_type()] % data
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/__init__.py", line 36, in __getattr__
app_1     |     return getattr(connections[DEFAULT_DB_ALIAS], item)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
app_1     |     res = instance.__dict__[self.name] = self.func(instance)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 196, in data_types
app_1     |     if self.features.supports_microsecond_precision:
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
app_1     |     res = instance.__dict__[self.name] = self.func(instance)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/mysql/features.py", line 52, in supports_microsecond_precision
app_1     |     return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
app_1     |     res = instance.__dict__[self.name] = self.func(instance)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 371, in mysql_version
app_1     |     with self.temporary_connection():
app_1     |   File "/opt/miniconda/lib/python2.7/contextlib.py", line 17, in __enter__
app_1     |     return self.gen.next()
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/base/base.py", line 462, in temporary_connection
app_1     |     cursor = self.cursor()
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/base/base.py", line 164, in cursor
app_1     |     cursor = self.make_cursor(self._cursor())
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
app_1     |     self.ensure_connection()
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
app_1     |     self.connect()
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
app_1     |     six.reraise(dj_exc_type, dj_exc_value, traceback)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
app_1     |     self.connect()
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
app_1     |     self.connection = self.get_new_connection(conn_params)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
app_1     |     conn = Database.connect(**conn_params)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
app_1     |     return Connection(*args, **kwargs)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
app_1     |     super(Connection, self).__init__(*args, **kwargs2)
app_1     | django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'db' (111)")
worker_1  | [   INFO   ] MusicExtractorSVM: no classifier models were configured by default
db_1      | 2019-07-31T23:12:14.383015Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12464449
db_1      | 2019-07-31T23:12:14.384727Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1      | 2019-07-31T23:12:14.384755Z 0 [Note] Shutting down plugin 'MEMORY'
db_1      | 2019-07-31T23:12:14.384765Z 0 [Note] Shutting down plugin 'CSV'
db_1      | 2019-07-31T23:12:14.384773Z 0 [Note] Shutting down plugin 'sha256_password'
db_1      | 2019-07-31T23:12:14.384778Z 0 [Note] Shutting down plugin 'mysql_native_password'
db_1      | 2019-07-31T23:12:14.384951Z 0 [Note] Shutting down plugin 'binlog'
db_1      | 2019-07-31T23:12:14.386195Z 0 [Note] mysqld: Shutdown complete
db_1      | 
db_1      | 
db_1      | MySQL init process done. Ready for start up.
db_1      | 
db_1      | 2019-07-31T23:12:14.656855Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1      | 2019-07-31T23:12:14.658927Z 0 [Note] mysqld (mysqld 5.7.27) starting as process 1 ...
db_1      | 2019-07-31T23:12:14.662696Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1      | 2019-07-31T23:12:14.662735Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1      | 2019-07-31T23:12:14.662744Z 0 [Note] InnoDB: Uses event mutexes
db_1      | 2019-07-31T23:12:14.662752Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1      | 2019-07-31T23:12:14.662759Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1      | 2019-07-31T23:12:14.662766Z 0 [Note] InnoDB: Using Linux native AIO
db_1      | 2019-07-31T23:12:14.663159Z 0 [Note] InnoDB: Number of pools: 1
db_1      | 2019-07-31T23:12:14.663306Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1      | 2019-07-31T23:12:14.665696Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1      | 2019-07-31T23:12:14.677953Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1      | 2019-07-31T23:12:14.680845Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1      | 2019-07-31T23:12:14.693177Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1      | 2019-07-31T23:12:14.703568Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1      | 2019-07-31T23:12:14.703662Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1      | 2019-07-31T23:12:14.735252Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1      | 2019-07-31T23:12:14.736336Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1      | 2019-07-31T23:12:14.736357Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1      | 2019-07-31T23:12:14.737310Z 0 [Note] InnoDB: 5.7.27 started; log sequence number 12464449
db_1      | 2019-07-31T23:12:14.737479Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1      | 2019-07-31T23:12:14.737713Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1      | 2019-07-31T23:12:14.743461Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190731 23:12:14
db_1      | 2019-07-31T23:12:14.744497Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1      | 2019-07-31T23:12:14.744860Z 0 [Warning] CA certificate ca.pem is self signed.
db_1      | 2019-07-31T23:12:14.747035Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1      | 2019-07-31T23:12:14.747099Z 0 [Note] IPv6 is available.
db_1      | 2019-07-31T23:12:14.747117Z 0 [Note]   - '::' resolves to '::';
db_1      | 2019-07-31T23:12:14.747143Z 0 [Note] Server socket created on IP: '::'.
db_1      | 2019-07-31T23:12:14.748835Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1      | 2019-07-31T23:12:14.762606Z 0 [Note] Event Scheduler: Loaded 0 events
db_1      | 2019-07-31T23:12:14.762893Z 0 [Note] mysqld: ready for connections.
db_1      | Version: '5.7.27'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
app_1     | [   INFO   ] MusicExtractorSVM: no classifier models were configured by default
worker_1  | [2019-08-01 01:12:17,993: WARNING/MainProcess] celery@7b491a5d3e42 ready.
app_1     | bower jquery#2.2.4          not-cached https://github.com/jquery/jquery-dist.git#2.2.4
app_1     | bower jquery#2.2.4             resolve https://github.com/jquery/jquery-dist.git#2.2.4
app_1     | bower bootstrap#3.3.7       not-cached https://github.com/twbs/bootstrap.git#3.3.7
app_1     | bower bootstrap#3.3.7          resolve https://github.com/twbs/bootstrap.git#3.3.7
app_1     | bower angular#1.2.26        not-cached https://github.com/angular/bower-angular.git#1.2.26
app_1     | bower angular#1.2.26           resolve https://github.com/angular/bower-angular.git#1.2.26
app_1     | bower font-awesome#4.4.0    not-cached https://github.com/FortAwesome/Font-Awesome.git#4.4.0
app_1     | bower font-awesome#4.4.0       resolve https://github.com/FortAwesome/Font-Awesome.git#4.4.0
[...]
app_1     | bootstrap#3.3.7 bower_components/bootstrap
app_1     | └── jquery#2.2.4
app_1     | 
app_1     | eve-raphael#0.5.0 bower_components/eve-raphael
app_1     | 
app_1     | SoundManager2#V2.97a.20150601 bower_components/SoundManager2
app_1     | [   INFO   ] MusicExtractorSVM: no classifier models were configured by default
app_1     | Traceback (most recent call last):
app_1     |   File "/srv/app/manage.py", line 7, in <module>
app_1     |     execute_from_command_line(sys.argv)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
app_1     |     utility.execute()
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
app_1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
app_1     |     self.execute(*args, **cmd_options)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
app_1     |     output = self.handle(*args, **options)
app_1     |   File "/srv/lib/telemeta/telemeta/management/commands/telemeta-create-admin-user.py", line 17, in handle
app_1     |     if not admin:
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/query.py", line 170, in __nonzero__
app_1     |     return type(self).__bool__(self)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/query.py", line 166, in __bool__
app_1     |     self._fetch_all()
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
app_1     |     self._result_cache = list(self.iterator())
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
app_1     |     results = compiler.execute_sql()
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
app_1     |     cursor.execute(sql, params)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
app_1     |     return self.cursor.execute(sql, params)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
app_1     |     six.reraise(dj_exc_type, dj_exc_value, traceback)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
app_1     |     return self.cursor.execute(sql, params)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
app_1     |     return self.cursor.execute(query, args)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
app_1     |     self.errorhandler(self, exc, value)
app_1     |   File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
app_1     |     raise errorclass, errorvalue
app_1     | django.db.utils.ProgrammingError: (1146, "Table 'telemeta.auth_user' doesn't exist")
app_1     | [   INFO   ] MusicExtractorSVM: no classifier models were configured by default

```

**Comment by AnasGhrab** [comment]
I had no problem on localhost OS X.

**Comment by AnasGhrab** [comment]
Je pense que le problème est celui-ci : https://cweiske.de/tagebuch/docker-mysql-available.htm

**Comment by AnasGhrab** [comment]
The problem does not exist anymore.
