### ISSUE TITLE
Localisation Arabic

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#24]
Hi,

I've started creating an Arabic localisation. I have make an ar directory in localisation ans pages and translated the .po files, and generated the .mo files. After reinstallling telemeta (sudo python setup.py install), it seems that the hole application follows the langage used by the super-user. Is that normal ? Where to define the default language for all users.

Besides, I have a problem accessing the public pages (admin pages work). I get the error 500 :

Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/views/home.py", line 76, in home
   return HttpResponse(template.render(context))

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
   return self._render(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
   return self.nodelist.render(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
   bit = self.render_node(node, context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
   return node.render(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
   return compiled_parent._render(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
   return self.nodelist.render(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
   bit = self.render_node(node, context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
   return node.render(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
   result = block.nodelist.render(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
   bit = self.render_node(node, context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
   return node.render(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
   result = block.nodelist.render(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
   bit = self.render_node(node, context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
   return node.render(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 891, in render
   output = self.filter_expression.resolve(context)

 File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 613, in resolve
   new_obj = func(obj, *arg_vals)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/templatetags/telemeta_utils.py", line 304, in render_flatpage
   parts = publish_parts(source=smart_str(parsed), writer_name="html4css1", settings_overrides={})

 File "/usr/local/lib/python2.7/dist-packages/docutils/core.py", line 448, in publish_parts
   enable_exit_status=enable_exit_status)

 File "/usr/local/lib/python2.7/dist-packages/docutils/core.py", line 662, in publish_programmatically
   output = pub.publish(enable_exit_status=enable_exit_status)

 File "/usr/local/lib/python2.7/dist-packages/docutils/core.py", line 217, in publish
   self.settings)

 File "/usr/local/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 72, in read
   self.parse()

 File "/usr/local/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 78, in parse
   self.parser.parse(self.input, document)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/__init__.py", line 172, in parse
   self.statemachine.run(inputlines, document, inliner=self.inliner)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 170, in run
   input_source=document['source'])

 File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
   context, state, transitions)

 File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
   return method(match, context, next_state)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2961, in text
   self.section(title.lstrip(), source, style, lineno + 1, messages)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 327, in section
   self.new_subsection(title, lineno, messages)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
   node=section_node, match_titles=True)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
   node=node, match_titles=match_titles)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 195, in run
   results = StateMachineWS.run(self, input_lines, input_offset)

 File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
   context, state, transitions)

 File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
   return method(match, context, next_state)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2726, in underline
   self.section(title, source, style, lineno - 1, messages)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 327, in section
   self.new_subsection(title, lineno, messages)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
   node=section_node, match_titles=True)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
   node=node, match_titles=match_titles)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 195, in run
   results = StateMachineWS.run(self, input_lines, input_offset)

 File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
   context, state, transitions)

 File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
   return method(match, context, next_state)

 File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2933, in text
   line=lineno)

 File "/usr/local/lib/python2.7/dist-packages/docutils/utils/__init__.py", line 235, in severe
   return self.system_message(self.SEVERE_LEVEL, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/docutils/utils/__init__.py", line 193, in system_message
   raise SystemMessage(msg, level)

SystemMessage: <string>:51: (SEVERE/4) Missing matching underline for section title overline.

========
\u062a\u062a\u0648\u0641\u0651\u0631 \u0648\u0631\u0634\u0629 \u0627\u0644\u062a\u0631\u0645\u064a\u0645 \u0627\u0644\u062a\u0627\u0628\u0639\u0629 \u0644\u062e\u0632\u064a\u0646\u0629 \u0627\u0644\u062a\u0633\u062c\u064a\u0644\u0627\u062a \u0627\u0644\u0635\u0648\u062a\u064a\u0629 \u0627\u0644\u0648\u0637\u0646\u064a\u0629 \u0639\u0644\u0649 \u0623\u062d\u062f\u062b \u0627\u0644\u0645\u0639\u062f\u0651\u0627\u062a \u0648\u0627\u0644\u062a\u0642\u0646\u064a\u0627\u062a \u0641\u064a \u0645\u064a\u062f\u0627\u0646 \u062a\u0631\u0645\u064a\u0645 \u0627\u0644\u0648\u062b\u0627\u0626\u0642 \u0627\u0644\u0635\u0648\u062a\u064a\u0629 \u0627\u0644\u062a\u064a \u0644\u062d\u0642\u062a \u0628\u0647\u0627 \u0623\u0636\u0631\u0627\u0631. \u0648\u0633\u062a\u0633\u062e\u0651\u0631 \u0627\u0644\u0648\u0631\u0634\u0629 \u0622\u062e\u0631 \u0645\u0627 \u062a\u0645\u0651 \u0627\u0644\u062a\u0648\u0635\u0651\u0644 \u0625\u0644\u064a\u0647 \u0641\u064a \u0645\u062c\u0627\u0644 \u0627\u0644\u0645\u0639\
u0627\u0644\u062c\u0629 \u0627\u0644\u0631\u0642\u0645\u064a\u0629 \u0644\u0644\u0635\u0648\u062a \u0644\u062a\u0631\u0645\u064a\u0645 \u0627\u0644\u062a\u0633\u062c\u064a\u0644\u0627\u062a \u0627\u0644\u0635\u0648\u062a\u064a\u0629 (\u0623\u0634\u0631\u0637\u0629\u060c \u0623\u0633\u0637\u0648\u0627\u0646\u0627\u062a) \u0627\u0644\u0645\u062a\u0636\u0631\u0651\u0631\u0629 \u0648\u0630\u0644\u0643 \u0628\u062a\u0648\u062e\u0651\u064a \u0643\u0644\u0651 \u0627\u0644\u062f\u0642\u0651\u0629 \u0648\u0627\u0644\u0645\u0647\u0627\u0631\u0629 \u0627\u0644\u0645\u0637\u0644\u0648\u0628\u062a\u064a\u0646. \u0648\u0628\u0639\u062f \u0639\u0645\u0644\u064a\u0651\u0629 \u0627\u0644\u062a\u0631\u0645\u064a\u0645 \u064a\u062a\u0645\u0651 \u0646\u0642\u0644 \u0647\u0630\u0647 \u0627\u0644\u062a\u0633\u062c\u064a\u0644\u0627\u062a \u0639\u0644\u0649 \u0623\u0648\u0639\u064a\u0629 \u062a\u0642\u0644\u064a\u062f\u064a\u0629 \u0623\u0648 \u0631\u0642\u0645\u064a\u0629 \u0645\u0645\u0651\u0627 \u064a\
u062c\u0639\u0644\u0647\u0627 \u0641\u064a \u0645\u0623\u0645\u0646 \u0645\u0646 \u0639\u0648\u0627\u0645\u0644 \u0627\u0644\u062a\u0644\u0641 \u0648\u064a\u0633\u0647\u0651\u0644 \u0627\u0644\u0625\u0637\u0651\u0644\u0627\u0639 \u0639\u0644\u064a\u0647\u0627 \u0648\u0646\u0634\u0631\u0647\u0627 \u0623\u0648 \u0625\u0639\u0627\u062f\u0629 \u0646\u0634\u0631\u0647\u0627.

**Comment by yomguy** [comment]
Hi Anas,
A separated repo has been created for managing locales : https://github.com/Parisson/Telemeta-locales
You need to follow the install instructions for development against Telemeta 1.5 so that the repo is initialized. I've started the "ar" in the dev branch so that you can write into the two .po files.
Afterwards, the "ar" languages needs to be added to the settings and chosen in the web UI from the profile page of the user.

**Comment by AnasGhrab** [comment]
I have made this : https://github.com/AnasGhrab/Telemeta-locales.

**Comment by yomguy** [comment]
Great! Can you try a Pull Request?
