### ISSUE TITLE
OAI data provider error for empty revision lists

### ISSUE THREAD

**Issue by yomguy** [Parisson/Telemeta#31]
Traceback (most recent call last):

  File "/home/parisson/crem_final2/local/lib/python2.7/site-packages/Django-1.6.8-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "./telemeta/views/home.py", line 123, in handle_oai_request
    return HttpResponse(provider.handle(args), mimetype='text/xml')

  File "./telemeta/interop/oai.py", line 243, in handle
    response.list_records(from_time, until_time, token, ids_only = (verb == 'ListIdentifiers'))

  File "./telemeta/interop/oai.py", line 456, in list_records
    data = self.datasource.list_records(offset, self.max_records_per_response, from_time, until_time)

  File "./telemeta/interop/oaidatasource.py", line 75, in list_records
    result.append(self.prepare_record(record))

  File "./telemeta/interop/oaidatasource.py", line 48, in prepare_record
    ctime = record.get_revision().time

  File "./telemeta/models/resource.py", line 61, in get_revision
    return Revision.objects.filter(element_type=self.element_type, element_id=self.id).order_by('-time')[0]

  File "/home/parisson/crem_final2/local/lib/python2.7/site-packages/Django-1.6.8-py2.7.egg/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]

IndexError: list index out of range

<WSGIRequest
path:/oai/,
GET:<QueryDict: {u'verb': [u'ListIdentifiers'], u'resumptionToken': [u',,44500']}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': '',
 u'CSRF_COOKIE': u'Bo7WNQNhHbnF1qYIGK6FDO6K9Th6GdHy',
 'DOCUMENT_ROOT': '/usr/share/nginx/html',
 'HTTP_ACCEPT_ENCODING': 'identity',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': 'archives.crem-cnrs.fr',
 'HTTP_USER_AGENT': 'Python-urllib/3.3',
 'PATH_INFO': u'/oai/',
 'QUERY_STRING': 'resumptionToken=%2C%2C44500&verb=ListIdentifiers',
 'REMOTE_ADDR': '193.48.96.156',
 'REMOTE_PORT': '5803',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/oai/?resumptionToken=%2C%2C44500&verb=ListIdentifiers',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'archives.crem-cnrs.fr',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.node': 'crem2',
 'uwsgi.version': '2.0.9',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x20f2c00>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x5bac918>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>

**Comment by yomguy** [comment]
Related error:



Traceback (most recent call last):

  File "/home/parisson/crem_final2/local/lib/python2.7/site-packages/Django-1.6.8-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "./telemeta/views/home.py", line 123, in handle_oai_request
    return HttpResponse(provider.handle(args), mimetype='text/xml')

  File "./telemeta/interop/oai.py", line 251, in handle
    xml = doc_to_string(response.doc)

  File "./telemeta/interop/oai.py", line 102, in doc_to_string
    doc2 = libxml2.parseDoc(doc.toxml(encoding="utf-8"))

  File "/usr/lib/python2.7/dist-packages/libxml2.py", line 1271, in parseDoc
    if ret is None:raise parserError('xmlParseDoc() failed')

parserError: xmlParseDoc() failed


<WSGIRequest
path:/oai/,
GET:<QueryDict: {u'verb': [u'GetRecord'], u'metadataPrefix': [u'oai_dc'], u'identifier': [u'oai:crem-cnrs:items:CNRSMH_E_1996_013_001_003_029']}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': '',
 u'CSRF_COOKIE': u'A0srijEwG1cZJwGs0MhoAwMNOxLehAXh',
 'DOCUMENT_ROOT': '/usr/share/nginx/html',
 'HTTP_ACCEPT_ENCODING': 'identity',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': 'archives.crem-cnrs.fr',
 'HTTP_USER_AGENT': 'Python-urllib/3.3',
 'PATH_INFO': u'/oai/',
 'QUERY_STRING': 'metadataPrefix=oai_dc&verb=GetRecord&identifier=oai%3Acrem-cnrs%3Aitems%3ACNRSMH_E_1996_013_001_003_029',
 'REMOTE_ADDR': '193.48.96.156',
 'REMOTE_PORT': '45320',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/oai/?metadataPrefix=oai_dc&verb=GetRecord&identifier=oai%3Acrem-cnrs%3Aitems%3ACNRSMH_E_1996_013_001_003_029',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'archives.crem-cnrs.fr',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.node': 'crem2',
 'uwsgi.version': '2.0.9',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x20f2c00>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x6e431f8>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
