### ISSUE TITLE
Recherche

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#32]
Quand j'essaie de lancer une recherche, j'obtiens l'erreur suivante :  

Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
   return self.dispatch(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
   return handler(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/list.py", line 137, in get
   self.object_list = self.get_queryset()

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/views/home.py", line 350, in get_queryset
   res = func(value)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/views/home.py", line 303, in <lambda>
   self.collections.quick_search(value),

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/models/query.py", line 275, in quick_search
   from telemeta.models.media import MediaCollection

ImportError: No module named media

**Comment by yomguy** [comment]
Je viens de publier 1.5.1. Tu peux donc mettre à jour ta branch dev ou master ;)
Si un pb persiste, il faut faire le ménage des .pyc:
```
find ./ -iname "*.pyc" -exec rm {} \;
```

**Comment by AnasGhrab** [comment]
C'est fait, mais le problème persiste...

**Comment by yomguy** [comment]
Juste pour être sûr (car je n'ai plus cette erreur):
```
./manage.py shell
>>> import telemeta
>>> telemeta.__file__
>>> telemeta.__version__
```
?

**Comment by yomguy** [comment]
Désolé Anas, il manquait un merge :(
La 1.5.1 est à jour et devrit passer désormais !

**Comment by AnasGhrab** [comment]
Toujours même erreurs.

Pour la recherche : 

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/views/home.py", line 303, in <lambda>
   self.collections.quick_search(value),

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/models/query.py", line 275, in quick_search
   from telemeta.models.media import MediaCollection

ImportError: No module named media

En essayant de changer le mot de passe : 

 File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 456, in _reverse_with_prefix
   (lookup_view_s, args, kwargs, len(patterns), patterns))

NoReverseMatch: Reverse for 'password_change_done' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

J'ai installé la version dev et j'ai : 

In [1]: import telemeta

In [2]: telemeta.__file__
Out[2]: '/usr/local/lib/python2.7/dist-packages/Telemeta-1.5.2-py2.7.egg/telemeta/__init__.pyc'

In [3]: telemeta.__version__
Out[3]: '1.5.2'

Je remarque aussi le Géo-Navigateur ne m'affiche plus NoData comme d'habitude, mais une erreur : 

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5-py2.7.egg/telemeta/models/query.py", line 134, in countries
   for continent in country.continents():

AttributeError: 'NoneType' object has no attribute 'continents'

**Comment by yomguy** [comment]
Ces erreurs sont liées à 1.5 (Telemeta-1.5-py2.7.egg) et non 1.5.1 ou 1.5.2.
Vérifie bien que ton site ou ta sandbox fait bien appel à la dernière version en passant par ./manage.py shell ;)

**Comment by AnasGhrab** [comment]
J'ai redémarré le serveur et là ça marche... je ne sais pas pourquoi :)

**Comment by yomguy** [comment]
As-tu bien redémarré ton service (uwsgi, apache ?) après upgrade ?

**Comment by AnasGhrab** [comment]
Oui, c'était bien ça. Il fallait redémarrer le service. ;)

**Comment by yomguy** [comment]
OK ;)
