### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#53]
I dont know why, I can't delete any user anymore. I get this error 500 :

Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 465, in wrapper
   return self.admin_site.admin_view(view)(*args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 99, in _wrapped_view
   response = view_func(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
   response = view_func(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 198, in inner
   return view(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
   return bound_func(*args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 99, in _wrapped_view
   response = view_func(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
   return func(self, *args2, **kwargs2)

 File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 371, in inner
   return func(*args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1490, in delete_view
   [obj], opts, request.user, self.admin_site, using)

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/util.py", line 137, in get_deleted_objects
   to_delete = collector.nested(format_callback)

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/util.py", line 191, in nested
   roots.extend(self._nested(root, seen, format_callback))

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/util.py", line 174, in _nested
   children.extend(self._nested(child, seen, format_callback))

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/util.py", line 176, in _nested
   ret = [format_callback(obj)]

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/util.py", line 135, in format_callback
   force_text(obj))

 File "/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py", line 100, in force_text
   s = s.__unicode__()

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5.1-py2.7.egg/telemeta/models/system.py", line 127, in __unicode__
   return self.keywords

AttributeError: 'Search' object has no attribute 'keywords'

<WSGIRequest
path:/admin/django/auth/user/19/delete/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
'PATH_INFO': u'/admin/django/auth/user/19/delete/',

**Comment by AnasGhrab** [comment]
What is strange, is that another Admin-user can delete users...

**Comment by yomguy** [comment]
The related search strings were indeed malformed. Thanks Anas ;)
