### ISSUE TITLE
ValueError: The 'file' attribute has no file associated with it.

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#63]
```
Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5.1-py2.7.egg/telemeta/views/item.py", line 232, in related_media_item_download
   filename = media.file.path.split(os.sep)[-1]

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/files.py", line 58, in _get_path
   self._require_file()

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/files.py", line 41, in _require_file
   raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)

ValueError: The 'file' attribute has no file associated with it.


<WSGIRequest
path:/archives/items/D-0019/related/64/download/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
```

**Comment by yomguy** [comment]
I think this have been fixed recently. Could you switch to dev branch because 1.5.1 is master at the moment ;)

**Comment by AnasGhrab** [comment]
While trying to install the dev branch : 

```
Processing Telemeta-1.5.2-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/Telemeta-1.5.2-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/Telemeta-1.5.2-py2.7.egg
Extracting Telemeta-1.5.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/Telemeta-1.5.2-py2.7.egg/telemeta/management/commands/telemeta-cleanup.py', 22, 32, "            if 'cache' in args::\n"))

Telemeta 1.5.2 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/Telemeta-1.5.2-py2.7.egg
Processing dependencies for Telemeta==1.5.2
error: Django 1.6.11 is installed but django==1.6.10 is required by set(['timeside'])
```

With witch version of TimeSide does the dev branch work ? I've tried both with the dev TimeSide and the master TimeSide, I've got the same error..

**Comment by yomguy** [comment]
Hi Anas,
So good to see you! ;)
The dev branch of Telemeta should be better with the dev branch of TimeSide.

**Comment by AnasGhrab** [comment]
TimeSide installs 1.6.10 : 
https://github.com/Parisson/TimeSide/issues/72

**Comment by yomguy** [comment]
Can we close this bug as Parisson/TimeSide#72 is fixed?

**Comment by AnasGhrab** [comment]
The install of TimeSide==0.8 (dev) gave me an Internal Server Error (http://phonotheque.cmam.tn/), even using Telemeta dev..

**Comment by AnasGhrab** [comment]
The install of TimeSide==0.8 (dev) gave me an Internal Server Error (http://phonotheque.cmam.tn/), even using Telemeta dev.. . I open a new Issue for this..
