### ISSUE TITLE
Après la mise à jour, erreur 500 

### ISSUE THREAD

**Issue by Hermimanoubia** [Parisson/Telemeta#80]
Erreur 500 au niveau de l'enregistrement des modifications et même au niveau d'ajout d'un item.

**Comment by yomguy** [comment]
Avez-vous accès aux logs du serveur web ?
Si non, sur quel site obtenez-vous l'erreur ?

**Comment by Hermimanoubia** [comment]
Je suis Manoubia Hermi documentaliste  dans la phonothèque Nationale du Centre des Musiques Arabes et Méditerranéennes (CMAM)

J’ai trouvé l’erreur su notre site

Cordialement

Manoubia

**Comment by yomguy** [comment]
Pouvez-vous nous donner également l'URL de votre navigateur qui vous donne l'erreur ?
/cc @AnasGhrab

**Comment by Hermimanoubia** [comment]
http://phonotheque.cmam.tn/archives/items/FN_CMAM_V072015_01/edit/

**Comment by yomguy** [comment]
Merci !
@AnasGhrab, peux-tu voir les logs ?

**Comment by Hermimanoubia** [comment]
Oui je peux les voir.

**Comment by AnasGhrab** [comment]
Oui, cela concerne l'édition de [toutes] les fiches. Erreur 500 lors de l'enregistrement.

```
Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/views/generic/base.py", line 69, in view
   return self.dispatch(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/utils/decorators.py", line 29, in _wrapper
   return bound_func(*args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/contrib/auth/decorators.py", line 22, in _wrapped_view
   return view_func(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/utils/decorators.py", line 25, in bound_func
   return func(self, *args2, **kwargs2)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/views/item.py", line 515, in dispatch
   return super(ItemEditView, self).dispatch(*args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/views/generic/base.py", line 87, in dispatch
   return handler(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/extra_views/advanced.py", line 157, in post
   return super(BaseUpdateWithInlinesView, self).post(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/extra_views/advanced.py", line 111, in post
   return self.forms_valid(form, inlines)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/views/item.py", line 482, in forms_valid
   item = form.save()

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/forms/models.py", line 446, in save
   construct=False)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/forms/models.py", line 99, in save_instance
   instance.save()

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/models/item.py", line 193, in save
   super(MediaItem, self).save(force_insert, force_update, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/models/core.py", line 148, in save
   super(ModelCore, self).save(force_insert, force_update, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/db/models/base.py", line 545, in save
   force_update=force_update, update_fields=update_fields)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/db/models/base.py", line 582, in save_base
   update_fields=update_fields, raw=raw, using=using)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/dispatch/dispatcher.py", line 185, in send
   response = receiver(signal=self, sender=sender, **named)

 File "/usr/local/lib/python2.7/dist-packages/django_haystack-2.4.0-py2.7.egg/haystack/signals.py", line 52, in handle_save
   index.update_object(instance, using=using)

 File "/usr/local/lib/python2.7/dist-packages/django_haystack-2.4.0-py2.7.egg/haystack/indexes.py", line 282, in update_object
   backend.update(self, [instance])

 File "/usr/local/lib/python2.7/dist-packages/django_haystack-2.4.0-py2.7.egg/haystack/backends/elasticsearch_backend.py", line 191, in update
   bulk_index(self.conn, prepped_docs, index=self.index_name, doc_type='modelresult')

 File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 182, in bulk
   for ok, item in streaming_bulk(client, actions, **kwargs):

 File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 155, in streaming_bulk
   raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)

BulkIndexError: ('1 document(s) failed to index.', [{u'index': {u'_type': u'modelresult', u'_id': u'telemeta.mediaitem.70442', u'ok': True, u'_version': 4, u'_index': u'haystack'}}])


<WSGIRequest
path:/archives/items/FN_CMAM_V092015_01/edit/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'comment': [u''], u'related-0-id': [u''], u'identifiers-0-type': [u''], u'code': [u'FN_CMAM_V092015_01'], u'identifiers-0-item': [u'70442'], u'performances-0-musicians': [u''], u'performances-0-instruments_num': [u''], u'keyword_relations-1-id': [u''], u'performances-TOTAL_FORMS': [u'2'], u'location_comment': [u'Palais Ennejma Ezzahra'], u'related-INITIAL_FORMS': [u'0'], u'performances-1-alias': [u''], u'identifiers-INITIAL_FORMS': [u'0'], u'keyword_relations-INITIAL_FORMS': [u'0'], u'performances-INITIAL_FORMS': [u'0'], u'file': [u''], u'cultural_area': [u''], u'recorded_from_date': [u'07/09/2015'], u'related-1-url': [u''], u'related-1-item': [u'70442'], u'collector': [u'CMAM'], u'performances-0-id': [u''], u'related-MAX_NUM_FORMS': [u'1000'], u'identifiers-0-id': [u''], u'keyword_relations-0-id': [u''], u'identifiers-0-date_first': [u''], u'author': [u'Salma Bourouni _ piano'], u'old_code': [u''], u'performances-MAX_NUM_FORMS': [u'1000'], u'approx_duration': [u'0
0:53:50'], u'auto_period_access': [u'on'], u'keyword_relations-TOTAL_FORMS': [u'2'], u'language_iso': [u''], u'performances-0-alias': [u''], u'related-0-file': [u''], u'related-1-id': [u''], u'location': [u'1'], u'creator_reference': [u''], u'identifiers-0-date_last': [u''], u'collector_selection': [u''], u'csrfmiddlewaretoken': [u'e58enRAvHKhO75bR1zRvCPoNdBqTRKWZ'], u'related-0-url': [u''], u'keyword_relations-0-item': [u'70442'], u'keyword_relations-1-keyword': [u''], u'related-1-title': [u''], u'related-0-description': [u''], u'external_references': [u''], u'related-1-description': [u''], u'related-0-title': [u''], u'track': [u''], u'keyword_relations-0-keyword': [u''], u'performances-1-musicians': [u''], u'moda_execut': [u''], u'collection': [u'3930'], u'performances-1-media_item': [u'70442'], u'ethnic_group': [u''], u'identifiers-TOTAL_FORMS': [u'1'], u'identifiers-MAX_NUM_FORMS': [u'1'], u'performances-0-instrument': [u''], u'media_type': [u''], u'performances-0-media_item': [
u'70442'], u'public_access': [u'metadata'], u'performances-1-instrument': [u''], u'keyword_relations-MAX_NUM_FORMS': [u'1000'], u'related-1-file': [u''], u'identifiers-0-identifier': [u''], u'related-TOTAL_FORMS': [u'2'], u'context_comment': [u''], u'performances-1-id': [u''], u'language': [u''], u'alt_title': [u''], u'url': [u''], u'related-1-credits': [u''], u'title': [u'R\xe9cital de piano'], u'related-0-item': [u'70442'], u'recorded_to_date': [u''], u'generic_style': [u''], u'performances-1-instruments_num': [u''], u'keyword_relations-1-item': [u'70442'], u'identifiers-0-notes': [u''], u'related-0-credits': [u''], u'vernacular_style': [u'']}>,
COOKIES:{'csrftoken': 'e58enRAvHKhO75bR1zRvCPoNdBqTRKWZ',
'messages': '78e5d06bf81b74c76a467faddb39cd0ba1cb0d10$[["__json_message",0,20,"You have successfully updated your item."],["__json_message",0,20,"You have successfully updated your item."],["__json_message",0,20,"You have successfully updated your item."],["__json_message",0,20,"You have successfully added your item."],["__json_message",0,20,"You have successfully added your item."],["__json_message",0,20,"You have successfully updated your item."],["__json_message",0,20,"You have successfully updated your item."],["__json_message",0,20,"You have successfully updated your item."],["__json_message",0,20,"You have successfully updated your item."],["__json_message",0,20,"You have successfully updated your item."]]',
'sessionid': '.eJyrVopPLC3JiC8tTi2KT0pMzk7NS1GyUkrJSsxLz9dLzs8rKcpM0gMp0YPKFuv55qek5jhB1eogG5AJ1GtcCwA2fR7r:1Zbkhh:aykWKBxpXNU3wS5-X205iZKvL-0'},
META:{'CONTENT_LENGTH': '9231',
'CONTENT_TYPE': 'multipart/form-data; boundary=---------------------------29438227816591',
u'CSRF_COOKIE': u'e58enRAvHKhO75bR1zRvCPoNdBqTRKWZ',
'DOCUMENT_ROOT': '/home/www/phono/',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
'HTTP_ACCEPT_LANGUAGE': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'csrftoken=e58enRAvHKhO75bR1zRvCPoNdBqTRKWZ; sessionid=".eJyrVopPLC3JiC8tTi2KT0pMzk7NS1GyUkrJSsxLz9dLzs8rKcpM0gMp0YPKFuv55qek5jhB1eogG5AJ1GtcCwA2fR7r:1Zbkhh:aykWKBxpXNU3wS5-X205iZKvL-0"; messages="78e5d06bf81b74c76a467faddb39cd0ba1cb0d10$[[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully updated your item.\\"]\\054[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully updated your item.\\"]\\054[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully updated your item.\\"]\\054[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully added your item.\\"]\\054[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully added your item.\\"]\\054[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully updated your item.\\"]\\054[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully updated your item.\\"]\\054[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully updated your item.\\"]\\054[\\"__json_message\
\"\\0540\\05420\\054\\"You have successfully updated your item.\\"]\\054[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully updated your item.\\"]]"',
[...]

```

**Comment by yomguy** [comment]
C'est donc un bug avec elasticsearch.
@AnasGhrab peux-tu me redonner la config haystack ds settings ?
Aussi, elasticsearch est-il bien démarré ?
Désolé pour ça, ms ce bug n'est pas reproductible ici, car nous développons de + en + avec docker et cette erreur n'apprait pas avec notre composition..
Enfin, il vaut mieux ne pas upgrader votre site de prod tant que la release n'a pas eu lieu.

**Comment by AnasGhrab** [comment]
@yomguy
Ci-joint la config de haystack : 

```
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': 'http://localhost:9200/',
        'INDEX_NAME': 'haystack',
    },
}
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 50
```

elasticsearch a bien démarré : 
```
curl 'http://localhost:9200/?pretty'
{
  "ok" : true,
  "status" : 200,
  "name" : "Grappler",
  "version" : {
    "number" : "0.20.6",
    "snapshot_build" : false
  },
  "tagline" : "You Know, for Search"
```

**Comment by AnasGhrab** [comment]
```
wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.deb;
sudo dpkg -i elasticsearch-1.7.2.deb
sudo update-rc.d elasticsearch defaults 95 10
sudo /etc/init.d/elasticsearch start
```

C'est réglé, merci yomguy ! Elasticsearch était à une version très ancienne.
