### ISSUE TITLE
Error when trying to remove a user

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#85]
```
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
   raise errorclass, errorvalue

ProgrammingError: (1146, "Table 'phono.timeside_selections' doesn't exist")
```

**Comment by yomguy** [comment]
whet is the output of
```
python manage.py migrate timeside
```
?

**Comment by AnasGhrab** [comment]
In settings, I have timeside.player and timeside.player. ```python manage.py migrate timeside``` gives : 
```
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/db/models/loading.py", line 190, in get_app
    raise ImproperlyConfigured("App with label %s could not be found" % app_label)
django.core.exceptions.ImproperlyConfigured: App with label timeside could not be found
```
If I add timeside to INSTALLED_APPS, I get  : 
```
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/db/models/loading.py", line 186, in get_app
    raise ImproperlyConfigured("App with label %s is missing a models.py module." % app_label)
django.core.exceptions.ImproperlyConfigured: App with label timeside is missing a models.py module.
```

**Comment by yomguy** [comment]
oops sorry
```
python manage.py migrate timeside.server
```

**Comment by AnasGhrab** [comment]
I had to that a long time ago.. but It wasn't in the doc... :( : 

```
python manage.py migrate timeside.server
Running migrations for server:
 - Migrating forwards to 0001_initial.
 > server:0001_initial
FATAL ERROR - The following SQL query failed: CREATE TABLE `timeside_selections` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `date_added` datetime NOT NULL, `date_modified` datetime NULL, `uuid` varchar(512) NOT NULL UNIQUE, `title` varchar(512) NOT NULL, `description` longtext NOT NULL, `author_id` integer NULL)
The error was: (1071, 'Specified key was too long; max key length is 1000 bytes')
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   = DROP TABLE `timeside_selections` CASCADE; []
   = DROP TABLE `timeside_selections_items` CASCADE; []
   = DROP TABLE `timeside_selections_selections` CASCADE; []
   = DROP TABLE `timeside_items` CASCADE; []
   = DROP TABLE `timeside_experiences` CASCADE; []
   = DROP TABLE `timeside_experiences_presets` CASCADE; []
   = DROP TABLE `timeside_experiences_experiences` CASCADE; []
   = DROP TABLE `timeside_processors` CASCADE; []
   = DROP TABLE `timeside_presets` CASCADE; []
   = DROP TABLE `timeside_results` CASCADE; []
   = DROP TABLE `timeside_tasks` CASCADE; []

 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: server:0001_initial
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/local/lib/python2.7/dist-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/usr/local/lib/python2.7/dist-packages/TimeSide-0.8-py2.7.egg/timeside/server/migrations/0001_initial.py", line 19, in forwards
    ('author', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='selections', null=True, on_delete=models.SET_NULL, to=orm['auth.User'])),
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 361, in create_table
    "columns": ', '.join([col for col in columns if col]),
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 1000 bytes')
```

**Comment by AnasGhrab** [comment]
It was here : 

https://github.com/Parisson/TimeSide/issues/81

At the end, I say : « it was ok after a good install of Elasticsearch.. »... but here... hmm..

**Comment by yomguy** [comment]
Arg, this error again :'( but I don't think it is related to elasticsearch.. TimeSide models are not so special and I'm afraid I cannot reproduce the bug. 
What is the type of your mysql database (InnoDB, MyISAM, other ?)

**Comment by AnasGhrab** [comment]
Your right. This error ``` Specified key was too long; max key length is 1000 bytes ``` is still there when I uncommented timeside.server (I think that a migrate stopped in mid-way and causes some trouble : I get error 500 when I try to delete a user : ```ProgrammingError: (1146, "Table 'phono.timeside_selections' doesn't exist")```).  

The variables of the mysql server tells me that the storage_engine is Inno_DB.

**Comment by AnasGhrab** [comment]
So, I commented timeside.server. To go back to the main problem : Error 500 when trying to remove a user : 

```
ProgrammingError: (1146, "Table 'phono.timeside_selections' doesn't exist")


<WSGIRequest
path:/admin/django/auth/user/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'action': [u'delete_selected'], u'select_across': [u'0'], u'csrfmiddlewaretoken': [u'TqkeIY1W39LBLBeDuyuUPtp8USXIe4UY'], u'_selected_action': [u'36'], u'index': [u'0']}>,
COOKIES:{'__utma': '15461495.1493276619.1447837438.1447837438.1447837438.1',
'__utmb': '15461495.2.10.1447837438',
'__utmc': '15461495',
'__utmt': '1',
'__utmz': '15461495.1447837438.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)',
'csrftoken': 'TqkeIY1W39LBLBeDuyuUPtp8USXIe4UY',
'sessionid': '.eJyrVopPLC3JiC8tTi2KT0pMzk7NS1GyUkrJSsxLz9dLzs8rKcpM0gMp0YPKFuv55qek5jhB1eogG5AJ1GtYCwA2eR7p:1Zyyjw:b2Z9pkUUgD7f5cQpXm3zL7Imq-A'},
META:{'CONTENT_LENGTH': '119',
'CONTENT_TYPE': 'application/x-www-form-urlencoded',
u'CSRF_COOKIE': u'TqkeIY1W39LBLBeDuyuUPtp8USXIe4UY',
'DOCUMENT_ROOT': '/home/www/phono/',
```

I'm wondering what is still looking for phono.timeside_selections...

**Comment by yomguy** [comment]
I really cannot reproduce the bug and I think this may be related to the configuration of your SQL tables or database. Could you please provide me some info about it (version, type, etc..)?
cheers
G
