### ISSUE TITLE
Unicode use in Markers

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#86]
I get a lot of the errors below. I do not know when they happen exactly but they are related to the use of Unicode (arabic text) in Markers. Maybe because of some hidden characters (not txt).. Maybe a check should be done before allowing the save...

```
Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/views/item.py", line 144, in item_detail
   title = ugettext('Item') + ' : ' + public_id + ' : ' + mess

TypeError: coercing to Unicode: need string or buffer, NoneType found


<WSGIRequest
path:/archives/markers/144465003475484385/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'__utma': '15461495.1291110344.1444931702.1444931702.1444931702.1',
'__utmb': '15461495.13.10.1444931702',
'__utmc': '15461495',
'__utmz': '15461495.1444931702.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)',
'csrftoken': 'BsjIZSajXNwskGmhodbaFgYVzUCkq2Vf',
'sessionid': '.eJyrVopPLC3JiC8tTi2KT0pMzk7NS1GyUkrJSsxLz9dLzs8rKcpM0gMp0YPKFuv55qek5jhB1eogG5AJ1GtsUQsAVVsfIw:1Zmmon:sFYi5qMTd8VBuPxeVZVL5BlUAxY'},
META:{u'CSRF_COOKIE': u'BsjIZSajXNwskGmhodbaFgYVzUCkq2Vf',
'DOCUMENT_ROOT': '/home/www/phono/',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, lzma, sdch',
'HTTP_ACCEPT_LANGUAGE': 'fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'csrftoken=BsjIZSajXNwskGmhodbaFgYVzUCkq2Vf; sessionid=".eJyrVopPLC3JiC8tTi2KT0pMzk7NS1GyUkrJSsxLz9dLzs8rKcpM0gMp0YPKFuv55qek5jhB1eogG5AJ1GtsUQsAVVsfIw:1Zmmon:sFYi5qMTd8VBuPxeVZVL5BlUAxY"; __utma=15461495.1291110344.1444931702.1444931702.1444931702.1; __utmb=15461495.13.10.1444931702; __utmc=15461495; __utmz=15461495.1444931702.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)',
'HTTP_HOST': 'phonotheque.cmam.tn',
'HTTP_REFERER': 'http://phonotheque.cmam.tn/desk/lists/',
'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36 OPR/32.0.1948.69',
'PATH_INFO': u'/archives/markers/144465003475484385/',
'PATH_TRANSLATED': '/wsgi.py/archives/markers/144465003475484385/',
'QUERY_STRING': '',
'REMOTE_ADDR': '197.15.86.187',
'REMOTE_PORT': '52568',
'REQUEST_METHOD': 'GET',
'REQUEST_URI': '/archives/markers/144465003475484385/',
[...]
```

**Comment by yomguy** [comment]
Salut Anas,
Aurais-tu des développeurs dans ton entourage pour nous donner un coup de main sur ces histoires de locales ?

**Comment by AnasGhrab** [comment]
Les développeurs que je connais travaillent avec PHP... j'essaierai d'approfondir la question...

**Comment by yomguy** [comment]
Il n'y a pas qqs pythonistes en Tunisie ? :p

**Comment by AnasGhrab** [comment]
La page d'une communauté sur le web. Le site qu'ils annoncent http://www.pythontunisia.com/ (fermé !).

Je n'ai pas l'impression que c'est bien répandu dans le monde professionnel des webmasters..

**Comment by yomguy** [comment]
Essaye p-e de te renseigner ds les universités / écoles d'informatique ? Il y a plein de bons sujets pour des stages.. Les 2 étudiants que nous avons eu cette année ne connaissaient pas python et il ont fait des prouesses ! Que ce soit pour pour python ou ruby, la "learning curve" comme on dit est très rapide et toutes les grosses plateformes y sont passé. Donc ya du boulot ;)
