### ISSUE TITLE
coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#95]
J'ai fait un `git pull` du master, puis `sudo python setup.py install`, l'accès au site n'est plus possible : 

```
Request URL:	http://phonotheque.cmam.tn/
Django Version:	1.6.11
Exception Type:	TypeError
Exception Value:	
coercing to Unicode: need string or buffer, NoneType found
Exception Location:	/usr/lib/python2.7/os.py in walk, line 276
Python Executable:	/usr/bin/python
Python Version:	2.7.3
```

**Comment by yomguy** [comment]
Aie! Il faut toujours tester avant de mettre en prod ! Fais-toi un 2nd site pour cela.
As-tu le traceback complet ? Il faudrait que je sache sur quel paramètre os.walk crashe..

**Comment by AnasGhrab** [comment]
```
Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/core/handlers/base.py", line 99, in get_response
   resolver_match = resolver.resolve(request.path_info)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/core/urlresolvers.py", line 337, in resolve
   for pattern in self.url_patterns:

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/core/urlresolvers.py", line 365, in url_patterns
   patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/core/urlresolvers.py", line 360, in urlconf_module
   self._urlconf_module = import_module(self.urlconf_name)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/utils/importlib.py", line 40, in import_module
   __import__(name)

 File "/home/www/phonotheque.cmam.tn/phono/urls.py", line 28, in <module>
   (r'^', include('telemeta.urls')),

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/conf/urls/__init__.py", line 26, in include
   urlconf_module = import_module(urlconf_module)

 File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/utils/importlib.py", line 40, in import_module
   __import__(name)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/urls.py", line 42, in <module>
   from telemeta.views import *

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/views/__init__.py", line 35, in <module>
   from telemeta.views.home import *

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/views/home.py", line 38, in <module>
   from telemeta.views.core import *

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/views/core.py", line 99, in <module>
   class TelemetaBaseMixin(object):

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/views/core.py", line 103, in TelemetaBaseMixin
   cache_tmp = TelemetaCache(settings.FILE_UPLOAD_TEMP_DIR)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/cache.py", line 46, in __init__
   self.files = self.get_files()

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.6-py2.7.egg/telemeta/cache.py", line 55, in get_files
   for root, dirs, files in os.walk(self.dir):

 File "/usr/lib/python2.7/os.py", line 276, in walk
   names = listdir(top)

TypeError: coercing to Unicode: need string or buffer, NoneType found


<WSGIRequest
path:/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'__utma': '15461495.1803380994.1448124098.1454105112.1454107806.81',
'__utmc': '15461495',
'__utmz': '15461495.1450987864.37.7.utmcsr=music22.ghrab.tn|utmccn=(referral)|utmcmd=referral|utmcct=/examples/barraq.html',
'_pk_id.1.2240': '429bb8bf7b31acf7.1453059844.32.1454108177.1454107806.',
'csrftoken': 'mz5v6cR2NrcAoFoJP2qze1NP0KUCvoeN',
'messages': 'a317a13c000d16b1c5be69ac36dca227201c1f95$[["__json_message",0,20,"You have successfully added your collection."],["__json_message",0,20,"You have successfully updated your collection."]]',
'sessionid': '.eJyrVopPLC3JiC8tTi2KT0pMzk7NS1GyUkrJSsxLz9dLzs8rKcpM0gMp0YPKFuv55qek5jhB1eogG5AJ1GtYCwA2eR7p:1aM2de:HwPHkCh0WtgTsc48bn3NT3KgYjE'},
META:{'DOCUMENT_ROOT': '/home/www/phonotheque.cmam.tn/',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
'HTTP_ACCEPT_LANGUAGE': 'fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'sessionid=".eJyrVopPLC3JiC8tTi2KT0pMzk7NS1GyUkrJSsxLz9dLzs8rKcpM0gMp0YPKFuv55qek5jhB1eogG5AJ1GtYCwA2eR7p:1aM2de:HwPHkCh0WtgTsc48bn3NT3KgYjE"; messages="a317a13c000d16b1c5be69ac36dca227201c1f95$[[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully added your collection.\\"]\\054[\\"__json_message\\"\\0540\\05420\\054\\"You have successfully updated your collection.\\"]]"; csrftoken=mz5v6cR2NrcAoFoJP2qze1NP0KUCvoeN; __utma=15461495.1803380994.1448124098.1454105112.1454107806.81; __utmc=15461495; __utmz=15461495.1450987864.37.7.utmcsr=music22.ghrab.tn|utmccn=(referral)|utmcmd=referral|utmcct=/examples/barraq.html; _pk_id.1.2240=429bb8bf7b31acf7.1453059844.32.1454108177.1454107806.',
'HTTP_HOST': 'phonotheque.cmam.tn',
'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36',
'PATH_INFO': u'/',
'PATH_TRANSLATED': '/home/www/phonotheque.cmam.tn/phono/wsgi.py/',
'QUERY_STRING': '',
'REMOTE_ADDR': '197.0.42.128',
'REMOTE_PORT': '52041',
'REQUEST_METHOD': 'GET',
'REQUEST_URI': '/',
'SCRIPT_FILENAME': '/home/www/phonotheque.cmam.tn/phono/wsgi.py',
'SCRIPT_NAME': u'',
'SERVER_ADDR': '37.187.165.192',
'SERVER_ADMIN': 'anas.ghrab@gmail.com',
'SERVER_NAME': 'phonotheque.cmam.tn',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '<address>Apache/2.2.22 (Debian) Server at phonotheque.cmam.tn Port 80</address>\n',
'SERVER_SOFTWARE': 'Apache/2.2.22 (Debian)',
'mod_wsgi.application_group': '',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'phonotheque',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 3),
'wsgi.errors': <mod_wsgi.Log object at 0x7f2f7fda5270>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f2f7f333030>,
'wsgi.input': <mod_wsgi.Input object at 0x7f2f7fda5230>,
'wsgi.multiprocess': True,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 1)}>
```

**Comment by yomguy** [comment]
OK pb avec le dossier cache. Quelles sont les valeurs de

TELEMETA_CACHE_DIR = os.path.join(MEDIA_ROOT, 'cache')
TELEMETA_EXPORT_CACHE_DIR = os.path.join(MEDIA_ROOT, 'export')
TELEMETA_DATA_CACHE_DIR = os.path.join(TELEMETA_CACHE_DIR, 'data')

ds ton settings ?

**Comment by AnasGhrab** [comment]
I've just made a ```git pull```.. this problem is still present...

**Comment by AnasGhrab** [comment]
Je crois que c'est ce problème qui m'empêche d'être à la dernière version. C'est sans doute en relation avec un affichage Unicode dans les models (voir par http://stackoverflow.com/questions/16169035/coercing-to-unicode-need-string-or-buffer-nonetype-found-when-rendering-in-dja).

Mais dans parmi les `models`, je ne sais pas de quel `model` il peut s'agir...

**Comment by AnasGhrab** [comment]
Ce problème `django coercing to Unicode: need string or buffer, NoneType found` est encore présent et il m'empêche d'être à la dernière version. Ça marche quand je me place sur commit datant du mois de janvier. Je ne sais plus à quelle version exactement ça bloque.

C'est assez certain que c'est en relation avec cette réponse que je trouve sur un forum :

```
This error happens when you have a ```__unicode__``` method that is a returning a field that is not entered. Any blank field is ```None``` and Python cannot convert ```None```, so you get the error.

In your case, the problem most likely is with the PCE model's ```__unicode__``` method, specifically the field its returning.

You can prevent this by returning a default value:

def __unicode__(self):
   return unicode(self.some_field) or u''
```

**Comment by maths28** [comment]
L'erreur se situe sur quel lien ?

**Comment by AnasGhrab** [comment]
Dès la première page..

**Comment by maths28** [comment]
Sur la plateforme du CMAM ou en local ?

**Comment by AnasGhrab** [comment]
Le problème est définitivement résolu en installant la dernière version avec le Docker.
