### ISSUE TITLE
Goto django 1.9

### ISSUE THREAD

**Issue by yomguy** [Parisson/Telemeta#99]

**Comment by AnasGhrab** [comment]
Excellent news !

**Comment by lluc** [comment]
:+1:

**Comment by AnasGhrab** [comment]
When trying the dj1.9 version with docker, I got : 

```
ImportError: No module named importlib
```

**Comment by thomasfillon** [comment]
Hi Anas !
Did you use the feature/dj1.9 branch ?

**Comment by AnasGhrab** [comment]
@thomasfillon : Yes, of course... !

**Comment by thomasfillon** [comment]
Ok thank you Anas.

The error you get here may be related to dependencies that also need to be updated.
The upgrade to Django 1.9 from 1.6 has induced some changes in requirements and database migrations.

Here is the updgrade process from Telemeta with django 1.6. 
**This upgrade process is not fully validated yet and may cause damage in your current database. Please do not try this on your production database.**

Upgrade process:
 
- Update git submodules (Timeside)
    - `git submodule update --init --remote --recursive `
- Update Parisson base docker image  and build:
    - ` docker pull parisson/timeside:latest-dev`  
    - `docker-compose -f docker-compose.yml -f env/dev.yml build`
- you also need to clear the existing Timeside Database (models have changed but it's safe for Telemeta models and database) 
      - `docker-compose -f docker-compose.yml -f env/dev.yml run app python manage.py migrate server zero`
      - `docker-compose -f docker-compose.yml -f env/dev.yml run app python manage.py migrate server`
- When upgrading from Django 1.6,  you also need to apply migrations for South to Django managed migrations:
    - `docker-compose -f docker-compose.yml -f env/dev.yml run app python manage.py migrate --fake-initial`
- At least, launch the Telemeta server:
    - `docker-compose -f docker-compose.yml -f env/dev.yml up
`

**Comment by thomasfillon** [comment]
Any feedback on this upgrading process would really be appreciate. Thanks !

**Comment by thomasfillon** [comment]
Regarding the current status of the feature/django1.9 branch, there are some issues regarding the url namespace. Actually, all telemeta views need to be declare with the `telemeta` namespace in urls.py otherwise django can not match the view and the url patterns.
I suspect that some old fashioned views and some ad-hoc code function need to be rewritten to match modern Django framework but this still need to be checked with @yomguy

**Comment by AnasGhrab** [comment]
@thomasfillon 
```
Zeus:Telemeta anas$ docker pull parisson/timeside:latest-dev
latest-dev: Pulling from parisson/timeside
386a066cd84a: Pull complete
68989880852f: Pull complete
c3a49a41ac92: Downloading [==========================================>        ]   226 MB/262.9 MB
d368507f091c: Download complete
40755864c98c: Download complete
182ac96e3309: Downloading [=============================>                     ] 193.5 MB/327.5 MB
ccd9ea92fe80: Download complete
d03f5a65d185: Download complete
d778cc8643cd: Download complete
ebfc56a85b71: Download complete
4d100610606b: Download complete
27825bd0117c: Download complete
72d898042580: Download complete
05c1552f3ea6: Download complete
117728e24899: Downloading
0a944d4954df: Waiting
74052b58e94a: Waiting
81a505d21a6d: Waiting
7fd109020c94: Waiting
f47b453c2c1c: Waiting
4998d8090344: Waiting
634f4084cc26: Waiting
unauthorized: authentication required
```

**Comment by thomasfillon** [comment]
You should retry because there is no authentification requirement I know about for accessing this public docker image ...

**Comment by AnasGhrab** [comment]
```
Zeus:Telemeta anas$ docker-compose -f docker-compose.yml -f env/dev.yml run app python manage.py migrate server zero
Starting telemeta_data_1
/srv/src/telemeta/telemeta/models/fields.py:124: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  class DurationField(models.Field):

/opt/miniconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

('timeside.plugins.diadems.irit_speech_4hz', None)
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/opt/miniconda/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/miniconda/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/miniconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/src/timeside/timeside/server/models.py", line 31, in <module>
    import timeside.core
  File "/srv/src/timeside/timeside/core/__init__.py", line 45, in <module>
    ts_package.discover_modules('plugins', 'timeside')#__name__)
  File "/srv/src/timeside/timeside/core/tools/package.py", line 44, in discover_modules
    in pkgutil.walk_packages(pkg_path, pkg_prefix)]
  File "/srv/src/timeside/timeside/core/tools/package.py", line 81, in import_module_with_exceptions
    raise e
ImportError: cannot import name store_parameters
```

**Comment by thomasfillon** [comment]
It seems that there is some problems regarding the git submodules and especially about the version of the Timeside-Diadems one.

I will try this on a fresh install to fully understand what happens. 

@AnasGhrab Did you start from a brand new directory ?

**Comment by AnasGhrab** [comment]
@thomasfillon Yes...

**Comment by thomasfillon** [comment]
OK I think I get it.

There is a mess with Timeside / Timeside-diadems version between sub-modules and docker image.
I'll do the clean up right now..

**Comment by thomasfillon** [comment]
the fault seems to be on the _Update git submodules_  command in the instructions above:

`git submodule update --init --remote --recursive` does not seem to be the proper way to do this.

**Comment by thomasfillon** [comment]
@AnasGhrab @lluc 
In the 'Upgrade process' above, please consider the following 

-  Update git submodules (Timeside)
   -     `git submodule update --init --recursive`

the `--remote` option was apparently updating the different submodule to the master branch head version.

Please, before properly updating your submodules, please clean up your submodule directories with:
`git submodule deinit -f .`

and then:
`git submodule update --init --recursive`

**Comment by AnasGhrab** [comment]
@thomasfillon

When I do ```docker-compose -f docker-compose.yml -f env/dev.yml run app python manage.py migrate --fake-initial``` I get ```manage.py: error: no such option: --fake-initial```

--fake-initial was created in 1.8, but I'm upgrading from Django 1.6 : 

https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-option---fake-initial

**Comment by AnasGhrab** [comment]
I'm working a fresh install. I have continued without --fake-initial, but I get : 

```
app_1         | bower soundmanager#V2.97a.20150601           resolved https://github.com/scottschiller/SoundManager2.git#V2.97a.20150601
app_1         |
app_1         | 0 static files copied to '/srv/static', 1838 unmodified.
db_1          | 2017-03-23T11:34:16.972269Z 11 [Note] Aborted connection 11 to db: 'telemeta' user: 'telemeta' host: '172.17.0.6' (Got an error reading communication packets)
db_1          | 2017-03-23T11:34:23.939879Z 12 [Note] Aborted connection 12 to db: 'telemeta' user: 'telemeta' host: '172.17.0.6' (Got an error reading communication packets)
app_1         | [23/Mar/2017 12:36:48] code 400, message Bad request syntax ('\x00\xf3\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x0f\x00/etc/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.1\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR')
app_1         | Traceback (most recent call last):
app_1         |   File "/opt/miniconda/lib/python2.7/SocketServer.py", line 596, in process_request_thread
app_1         |     self.finish_request(request, client_address)
app_1         |   File "/opt/miniconda/lib/python2.7/SocketServer.py", line 331, in finish_request
app_1         |     self.RequestHandlerClass(request, client_address, self)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 126, in __init__
app_1         |     super(WSGIRequestHandler, self).__init__(*args, **kwargs)
app_1         |   File "/opt/miniconda/lib/python2.7/SocketServer.py", line 652, in __init__
app_1         |     self.handle()
app_1         |   File "/opt/miniconda/lib/python2.7/wsgiref/simple_server.py", line 124, in handle
app_1         |     if not self.parse_request(): # An error code has been sent, just exit
app_1         |   File "/opt/miniconda/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
app_1         |     self.send_error(400, "Bad request syntax (%r)" % requestline)
app_1         |   File "/opt/miniconda/lib/python2.7/BaseHTTPServer.py", line 365, in send_error
app_1         |     self.send_response(code, message)
app_1         |   File "/opt/miniconda/lib/python2.7/BaseHTTPServer.py", line 396, in send_response
app_1         |     self.log_request(code)
app_1         |   File "/opt/miniconda/lib/python2.7/BaseHTTPServer.py", line 433, in log_request
app_1         |     self.requestline, str(code), str(size))
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 138, in log_message
app_1         |     msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
app_1         | UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 2: ordinal not in range(128)
app_1         | [23/Mar/2017 12:36:48] code 400, message Bad request syntax ('\x00\xde\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x0c\x00/favicon.ico\t\x00PATH_INFO\x0c\x00/favicon.ico\r\x00DOCUMENT_ROOT\x0f\x00/etc/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.1\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR')
app_1         | Traceback (most recent call last):
app_1         |   File "/opt/miniconda/lib/python2.7/SocketServer.py", line 596, in process_request_thread
app_1         |     self.finish_request(request, client_address)
app_1         |   File "/opt/miniconda/lib/python2.7/SocketServer.py", line 331, in finish_request
app_1         |     self.RequestHandlerClass(request, client_address, self)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 126, in __init__
app_1         |     super(WSGIRequestHandler, self).__init__(*args, **kwargs)
app_1         |   File "/opt/miniconda/lib/python2.7/SocketServer.py", line 652, in __init__
app_1         |     self.handle()
app_1         |   File "/opt/miniconda/lib/python2.7/wsgiref/simple_server.py", line 124, in handle
app_1         |     if not self.parse_request(): # An error code has been sent, just exit
app_1         |   File "/opt/miniconda/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
app_1         |     self.send_error(400, "Bad request syntax (%r)" % requestline)
app_1         |   File "/opt/miniconda/lib/python2.7/BaseHTTPServer.py", line 365, in send_error
app_1         |     self.send_response(code, message)
app_1         |   File "/opt/miniconda/lib/python2.7/BaseHTTPServer.py", line 396, in send_response
app_1         |     self.log_request(code)
app_1         |   File "/opt/miniconda/lib/python2.7/BaseHTTPServer.py", line 433, in log_request
app_1         |     self.requestline, str(code), str(size))
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 138, in log_message
app_1         |     msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
app_1         | UnicodeDecodeError: 'ascii' codec can't decode byte 0xde in position 2: ordinal not in range(128)
```

**Comment by thomasfillon** [comment]
@AnasGhrab Did you remove your last comments ?

**Comment by AnasGhrab** [comment]
@thomasfillon Yes.. I think I had to try again.. i've missed something ;)

**Comment by thomasfillon** [comment]
ok thanks

`--fake-initial` should be ok as the django version is updated to 1.8 or 1.9 in the feature/dj1.8, feature/dj1.9 branches respectively.

**Comment by AnasGhrab** [comment]
Here's what I did locally on my OS X for testing. After deleting containers, from the master branch of Telemeta : 

1. Change the docker-compose.yml to add the utf8 command;
2. ```docker-compose up```;
3. Merge the remotes/origin/feature/dj1.9
4. Start following the commands above..

But, I get : 

```
Zeus:Telemeta anas$ docker-compose -f docker-compose.yml -f env/dev.yml run app python manage.py migrate server zero
Starting telemeta_data_1
Starting telemeta_search_1
Starting telemeta_broker_1
Starting telemeta_db_1
/srv/src/telemeta/telemeta/models/fields.py:124: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  class DurationField(models.Field):

/opt/miniconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

System check identified some issues:

WARNINGS:
telemeta.UserProfile.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Operations to perform:
  Unapply all migrations: server
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    emit_post_migrate_signal(self.verbosity, self.interactive, connection.alias)
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/sql.py", line 50, in emit_post_migrate_signal
    using=db)
  File "/opt/miniconda/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/opt/miniconda/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py", line 85, in create_permissions
    ctype = ContentType.objects.db_manager(using).get_for_model(klass)
  File "/opt/miniconda/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 80, in get_for_model
    "Error creating new content types. Please make sure contenttypes "
RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.
```

Di I have to merge other branches ? /feature/html5 ? /feature/ts-server ?

**Comment by thomasfillon** [comment]
No, there is no other merge to perform.

Do you have changes in your models compared to the feature/dj1.9 branch ?

**Comment by AnasGhrab** [comment]
No

**Comment by thomasfillon** [comment]
Could you please give the output of `git submodule` ?

**Comment by AnasGhrab** [comment]
```
Zeus:Telemeta anas$ git submodule
 0d473861e930e91a4a85a1770d926a62c05b8268 doc/themes/pelican-bootstrap3 (v1.0-272-g0d47386)
 3f56ebfe3a5fe3ba1a802e50a746f8ce0a6fca42 lib/TimeSide (utils-1662-g3f56ebf)
 e7fd56599e9e22eddf92c1063419fec6ab82e15e telemeta/locale (heads/master)
 c2a0f19625f44ab2c3050b7784382ac7eb6939b0 telemeta/pages (heads/master)
```

**Comment by AnasGhrab** [comment]
I've tried again and it installed some other packages (I do not why not at the first time..) Now I have this : 

```

Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/opt/miniconda/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/opt/miniconda/lib/python2.7/site-packages/south/migration/__init__.py", line 200, in migrate_app
    applied_all = check_migration_histories(applied_all, delete_ghosts, ignore_ghosts)
  File "/opt/miniconda/lib/python2.7/site-packages/south/migration/__init__.py", line 79, in check_migration_histories
    for h in histories:
  File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/opt/miniconda/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/miniconda/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/miniconda/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/miniconda/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'telemeta.south_migrationhistory' doesn't exist")
```

**Comment by AnasGhrab** [comment]
It seems to be ok after another ```docker-compose up```. Sorry for all these messy comments.. I'd like to find exactly the good procedure.

**Comment by AnasGhrab** [comment]
Now it seems to be much, but it is labyrinthic ;) I had first to merge the dj1.8 before the dj1.9, then also the dev branch. Now I get this : 

```
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/defaulttags.py", line 513, in render
app_1         |     six.reraise(*exc_info)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/defaulttags.py", line 499, in render
app_1         |     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 596, in reverse
app_1         |     key)
app_1         | NoReverseMatch: u'djdt' is not a registered namespace
app_1         | [24/Mar/2017 12:25:07] "GET / HTTP/1.1" 500 150603
```

**Comment by thomasfillon** [comment]
The good procedure should be the one in my comment of the 22 february (except the git submodule command line).
If this procedure is not good, we should correct it.

**Comment by thomasfillon** [comment]
Sorry but I don't understand why you need to do all this merge ? why the dev branch ?

Currently only the feature/dj1.8 is working, the feature/dj1.9 has some problems related to views.
Would you mind testing only the feature/dj1.8 branch only for now ?

**Comment by AnasGhrab** [comment]
@thomasfillon 
I got a well working dj1.8. With the dj1.9, I get this error : 

```
app_1         | Traceback (most recent call last):
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
app_1         |     response = self.process_exception_by_middleware(e, request)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
app_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1         |   File "/srv/src/telemeta/telemeta/views/home.py", line 97, in home
app_1         |     return HttpResponse(template.render(context, request))
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
app_1         |     return self.template.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 206, in render
app_1         |     return self._render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
app_1         |     return self.nodelist.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 992, in render
app_1         |     bit = node.render_annotated(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
app_1         |     return self.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
app_1         |     return compiled_parent._render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
app_1         |     return self.nodelist.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 992, in render
app_1         |     bit = node.render_annotated(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
app_1         |     return self.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
app_1         |     result = block.nodelist.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 992, in render
app_1         |     bit = node.render_annotated(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
app_1         |     return self.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
app_1         |     result = block.nodelist.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 992, in render
app_1         |     bit = node.render_annotated(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
app_1         |     return self.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
app_1         |     result = block.nodelist.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 992, in render
app_1         |     bit = node.render_annotated(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
app_1         |     return self.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/defaulttags.py", line 513, in render
app_1         |     six.reraise(*exc_info)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/defaulttags.py", line 499, in render
app_1         |     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
app_1         |     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
app_1         |     (lookup_view_s, args, kwargs, len(patterns), patterns))
app_1         | NoReverseMatch: Reverse for 'telemeta-home' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
app_1         | Internal Server Error: /
app_1         | Traceback (most recent call last):
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
app_1         |     response = middleware_method(request, response)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 131, in process_response
app_1         |     bits[-2] += toolbar.render_toolbar()
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 64, in render_toolbar
app_1         |     return render_to_string('debug_toolbar/base.html', context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
app_1         |     return template.render(context, request)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
app_1         |     return self.template.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 206, in render
app_1         |     return self._render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
app_1         |     return self.nodelist.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 992, in render
app_1         |     bit = node.render_annotated(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
app_1         |     return self.render(context)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/defaulttags.py", line 513, in render
app_1         |     six.reraise(*exc_info)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/template/defaulttags.py", line 499, in render
app_1         |     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
app_1         |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 596, in reverse
app_1         |     key)
app_1         | NoReverseMatch: u'djdt' is not a registered namespace
app_1         | [25/Mar/2017 23:57:36] "GET / HTTP/1.1" 500 150875
```
